# -*- coding: utf-8 -*-
"""
Curriculo de Historia: 20 fichas por curso, dificultad creciente.

Progresion: de la nocion de tiempo personal (antes/despues, mi familia) en 2
anos, a las grandes civilizaciones y la cronologia por siglos en 7 anos. En
Infantil el tiempo se trabaja siempre desde lo vivido; las fechas y las edades
historicas aparecen solo en Primaria.
"""

from generar_fichas import b_colorear, b_concepto, b_contar, b_emparejar, b_unir
from bloques_texto import (
    b_clasificar, b_dibujar, b_escritura, b_lectura, b_ordenar, b_verdadero_falso,
)


CURSO_2 = [
    ("Este soy yo", "Reconocerse a sí mismo como punto de partida del tiempo.",
     lambda r: [b_dibujar(r, "Dibújate a ti. ¿De qué color tienes el pelo?", "Yo")]),
    ("Mi familia", "Identificar a las personas cercanas.",
     lambda r: [b_dibujar(r, "Dibuja a las personas que viven en tu casa.", "Mi familia")]),
    ("De día y de noche", "Primera noción de tiempo cíclico.",
     lambda r: [b_concepto(r, [("☀️", "de día"), ("🌙", "de noche"), ("⭐", "de noche")],
                           "Colorea de amarillo lo del DÍA y de azul lo de la NOCHE.")]),
    ("Bebé y mayor", "Noción de crecimiento.",
     lambda r: [b_concepto(r, [("👶", "bebé"), ("🧒", "mayor"), ("🍼", "bebé")],
                           "Rodea lo que usa un BEBÉ.")]),
    ("Antes y después", "Secuencia temporal de dos pasos.",
     lambda r: [b_ordenar(r, [("🥚 Huevo", 1), ("🐥 Pollito", 2)],
                          "Numera con 1 lo que pasa ANTES y con 2 lo que pasa DESPUÉS.")]),
    ("Me despierto", "Rutinas de la mañana.",
     lambda r: [b_ordenar(r, [("🛏️ Me despierto", 1), ("👕 Me visto", 2), ("🥣 Desayuno", 3)])]),
    ("Mi casa", "El espacio propio como referencia.",
     lambda r: [b_dibujar(r, "Dibuja tu casa por fuera.", "Mi casa")]),
    ("Cosas viejas y nuevas", "Discriminar lo antiguo de lo actual.",
     lambda r: [b_concepto(r, [("📻", "antiguo"), ("📱", "nuevo"), ("🕯️", "antiguo")],
                           "Rodea lo que es ANTIGUO, de cuando tus abuelos eran pequeños.")]),
    ("Los dinosaurios", "Primer contacto con un tiempo muy lejano.",
     lambda r: [b_colorear(r, 2, 4), b_dibujar(r, "Colorea el dinosaurio como más te guste.",
                                               "Mi dinosaurio", "mediano")]),
    ("Grande como un dinosaurio", "Comparar tamaños con referentes históricos.",
     lambda r: [b_concepto(r, [("🦕", "grande"), ("🐭", "pequeño"), ("🦖", "grande")],
                           "Rodea los animales GRANDES.")]),
    ("Sol y luna", "Consolidar el ciclo día-noche.",
     lambda r: [b_emparejar(r, 3)]),
    ("Me lavo los dientes", "Rutinas de higiene en secuencia.",
     lambda r: [b_ordenar(r, [("🪥 Cojo el cepillo", 1), ("🦷 Me lavo", 2), ("💧 Me enjuago", 3)])]),
    ("Mis abuelos", "Reconocer generaciones.",
     lambda r: [b_dibujar(r, "Dibuja a tus abuelos o a una persona mayor que quieras.", "Mis abuelos")]),
    ("¿Cuántos años tengo?", "Relacionar edad y número.",
     lambda r: [b_contar(r, 3, 3)]),
    ("El invierno y el verano", "Primera noción de estaciones.",
     lambda r: [b_concepto(r, [("❄️", "invierno"), ("🏖️", "verano"), ("🧣", "invierno")],
                           "Colorea lo que usamos en INVIERNO.")]),
    ("Comer y dormir", "Rutinas del final del día.",
     lambda r: [b_ordenar(r, [("🍽️ Ceno", 1), ("🛁 Me baño", 2), ("🛏️ Me duermo", 3)])]),
    ("Los cuentos de antes", "Aproximación a la tradición oral.",
     lambda r: [b_dibujar(r, "Dibuja tu cuento favorito.", "Mi cuento")]),
    ("El fuego", "Un descubrimiento muy antiguo, contado de forma simple.",
     lambda r: [b_colorear(r, 2, 4),
                b_concepto(r, [("🔥", "calienta"), ("❄️", "enfría")],
                           "Rodea lo que da CALOR.")]),
    ("Antes no había coches", "Cambio en los medios de transporte.",
     lambda r: [b_unir(r, [("🐴 Antes", "🐴"), ("🚗 Ahora", "🚗")],
                       "Une con el dibujo que corresponde.")]),
    ("Repaso: antes y ahora", "Consolidar la noción básica de cambio.",
     lambda r: [b_concepto(r, [("🦕", "hace mucho"), ("👶", "hace poco"), ("📱", "ahora")],
                           "Ordena del más ANTIGUO al más NUEVO escribiendo 1, 2 y 3.")]),
]

CURSO_3 = [
    ("El día y la noche", "Consolidar el ciclo diario.",
     lambda r: [b_clasificar(r, ["De día", "De noche"],
                             [("☀️ Sol", 0), ("🌙 Luna", 1), ("🏫 Colegio", 0),
                              ("😴 Dormir", 1), ("🍽️ Comer", 0), ("⭐ Estrellas", 1)])]),
    ("Mi día, paso a paso", "Secuenciar una jornada completa.",
     lambda r: [b_ordenar(r, [("Me levanto", 1), ("Voy al cole", 2),
                              ("Como", 3), ("Juego", 4), ("Me duermo", 5)])]),
    ("Las cuatro estaciones", "Reconocer el ciclo anual.",
     lambda r: [b_unir(r, [("Primavera", "🌸"), ("Verano", "🏖️"),
                           ("Otoño", "🍂"), ("Invierno", "❄️")],
                       "Une cada estación con su dibujo.")]),
    ("La primavera", "Rasgos de la estación.",
     lambda r: [b_colorear(r, 3, 5),
                b_dibujar(r, "Dibuja un árbol en primavera, lleno de flores.", "Primavera", "mediano")]),
    ("El otoño", "Rasgos de la estación.",
     lambda r: [b_concepto(r, [("🍂", "otoño"), ("🌰", "otoño"), ("🌻", "verano")],
                           "Rodea lo que es del OTOÑO.")]),
    ("Ayer, hoy y mañana", "Tres momentos del tiempo cercano.",
     lambda r: [b_ordenar(r, [("Ayer", 1), ("Hoy", 2), ("Mañana", 3)])]),
    ("Los dinosaurios herbívoros", "Clasificar por alimentación.",
     lambda r: [b_clasificar(r, ["Comía plantas", "Comía carne"],
                             [("🦕 Diplodocus", 0), ("🦖 T-Rex", 1),
                              ("🦕 Braquiosaurio", 0), ("🦖 Velociraptor", 1)])]),
    ("El huevo de dinosaurio", "Reproducción y ciclo vital.",
     lambda r: [b_dibujar(r, "Este huevo se está rompiendo. ¡Dibuja el dinosaurio que nace!",
                          "Mi dinosaurio bebé")]),
    ("Grande, mediano, pequeño", "Comparar dinosaurios por tamaño.",
     lambda r: [b_ordenar(r, [("🦟 Mosquito", 1), ("🐕 Perro", 2), ("🦕 Diplodocus", 3)],
                          "Numera del más PEQUEÑO (1) al más GRANDE (3).")]),
    ("Antes no había luz eléctrica", "Cambios en la vida cotidiana.",
     lambda r: [b_unir(r, [("Antes", "🕯️ Vela"), ("Ahora", "💡 Bombilla")],
                       "Une cada época con lo que se usaba para ver de noche.")]),
    ("Cómo íbamos antes", "Evolución del transporte.",
     lambda r: [b_clasificar(r, ["De antes", "De ahora"],
                             [("🐴 Caballo", 0), ("🚗 Coche", 1), ("🛶 Barca de remos", 0),
                              ("✈️ Avión", 1), ("🚂 Tren de vapor", 0), ("🚀 Cohete", 1)])]),
    ("Mi árbol de familia", "Relaciones entre generaciones.",
     lambda r: [b_dibujar(r, "Dibuja a tus abuelos arriba, a tus padres en medio y a ti abajo.",
                          "Mi familia")]),
    ("Los oficios", "Reconocer trabajos del entorno.",
     lambda r: [b_unir(r, [("🧑‍🚒 Bombero", "🔥"), ("👩‍⚕️ Médica", "🩺"),
                           ("👨‍🍳 Cocinero", "🍳"), ("👩‍🏫 Maestra", "📚")],
                       "Une cada oficio con lo que usa para trabajar.")]),
    ("Los días de la semana", "Nombrar y ordenar los siete días.",
     lambda r: [b_ordenar(r, [("Lunes", 1), ("Martes", 2), ("Miércoles", 3), ("Jueves", 4),
                              ("Viernes", 5), ("Sábado", 6), ("Domingo", 7)])]),
    ("La cueva prehistórica", "La vivienda más antigua.",
     lambda r: [b_dibujar(r, "Las personas de la prehistoria vivían en cuevas y pintaban "
                             "en las paredes. ¡Haz tu pintura de cueva!", "Mi pintura rupestre")]),
    ("Frío y calor", "Relacionar estación y ropa.",
     lambda r: [b_clasificar(r, ["Cuando hace frío", "Cuando hace calor"],
                             [("🧣 Bufanda", 0), ("🩳 Pantalón corto", 1), ("🧤 Guantes", 0),
                              ("🕶️ Gafas de sol", 1), ("🧥 Abrigo", 0), ("👙 Bañador", 1)])]),
    ("Mi cumpleaños", "El año como unidad de tiempo personal.",
     lambda r: [b_contar(r, 3, 5),
                b_dibujar(r, "Dibuja tu tarta de cumpleaños con tus velas.", "Mi cumple", "mediano")]),
    ("Los animales de antes", "Animales extinguidos frente a actuales.",
     lambda r: [b_clasificar(r, ["Ya no existen", "Existen hoy"],
                             [("🦕 Dinosaurio", 0), ("🐘 Elefante", 1), ("🦣 Mamut", 0),
                              ("🐅 Tigre", 1), ("🦖 T-Rex", 0), ("🐄 Vaca", 1)])]),
    ("El reloj y el tiempo", "Primer contacto con la medida del tiempo.",
     lambda r: [b_concepto(r, [("⏰", "mide el tiempo"), ("📏", "mide cosas"), ("⌛", "mide el tiempo")],
                           "Rodea lo que sirve para medir el TIEMPO.")]),
    ("Repaso: el tiempo que pasa", "Evaluación del curso.",
     lambda r: [b_ordenar(r, [("👶 Bebé", 1), ("🧒 Niño", 2), ("🧑 Adulto", 3), ("🧓 Abuelo", 4)]),
                b_clasificar(r, ["De antes", "De ahora"],
                             [("🕯️ Vela", 0), ("💡 Bombilla", 1), ("🐴 Caballo", 0), ("🚗 Coche", 1)])]),
]

CURSO_4 = [
    ("El mundo de los dinosaurios", "Situar a los dinosaurios en un pasado remoto.",
     lambda r: [b_lectura(r, "Los dinosaurios vivieron en la Tierra hace muchísimos años, "
                             "mucho antes de que existieran las personas. Unos comían plantas "
                             "y otros comían carne.",
                          [("¿Vivieron los dinosaurios con las personas?", "No"),
                           ("¿Qué comían?", "Unos plantas y otros carne")])]),
    ("Herbívoros y carnívoros", "Clasificar por alimentación.",
     lambda r: [b_clasificar(r, ["Herbívoro", "Carnívoro"],
                             [("Diplodocus", 0), ("Tiranosaurio", 1), ("Triceratops", 0),
                              ("Velociraptor", 1), ("Braquiosaurio", 0), ("Alosaurio", 1)])]),
    ("El Triceratops", "Conocer un dinosaurio concreto.",
     lambda r: [b_escritura(r, [("🦕", "TRICERATOPS")]),
                b_dibujar(r, "El Triceratops tenía tres cuernos. ¡Dibújalo y coloréalo!",
                          "Mi Triceratops", "mediano")]),
    ("¿Por qué desaparecieron?", "Noción de extinción.",
     lambda r: [b_verdadero_falso(r, [
         ("Los dinosaurios desaparecieron hace millones de años.", True),
         ("Hoy todavía quedan dinosaurios en el zoo.", False),
         ("Sabemos cómo eran gracias a sus huesos fósiles.", True)])]),
    ("Los fósiles", "Cómo conocemos el pasado.",
     lambda r: [b_lectura(r, "Un fósil es un hueso o una huella que se quedó guardado en la piedra "
                             "durante muchísimos años. Los científicos los buscan para saber cómo "
                             "eran los animales de antes.",
                          [("¿Qué es un fósil?", "Un hueso o huella guardado en la piedra"),
                           ("¿Para qué sirven?", "Para saber cómo eran los animales de antes")])]),
    ("La prehistoria", "La vida antes de la escritura.",
     lambda r: [b_clasificar(r, ["Prehistoria", "Ahora"],
                             [("🏹 Cazar con lanza", 0), ("🛒 Ir al súper", 1),
                              ("🕳️ Vivir en cuevas", 0), ("🏢 Vivir en pisos", 1),
                              ("🔥 Hacer fuego frotando", 0), ("🔦 Encender la luz", 1)])]),
    ("El descubrimiento del fuego", "Un hito de la humanidad.",
     lambda r: [b_lectura(r, "Hace mucho tiempo, las personas aprendieron a hacer fuego. "
                             "Gracias al fuego podían calentarse, cocinar la comida y "
                             "espantar a los animales peligrosos.",
                          [("¿Para qué servía el fuego?", "Calentarse, cocinar y espantar animales")])]),
    ("Pinturas rupestres", "El arte más antiguo.",
     lambda r: [b_dibujar(r, "En las cuevas pintaban bisontes y manos. Haz tu propia pintura "
                             "rupestre con las manos y algún animal.", "Mi cueva")]),
    ("El mamut", "Animales de la Edad de Hielo.",
     lambda r: [b_escritura(r, [("🦣", "MAMUT")]),
                b_verdadero_falso(r, [("El mamut era peludo porque hacía mucho frío.", True),
                                      ("El mamut se parecía a un elefante.", True),
                                      ("Los mamuts todavía existen.", False)])]),
    ("La rueda", "Un invento que lo cambió todo.",
     lambda r: [b_lectura(r, "La rueda es uno de los inventos más importantes. Antes había que "
                             "arrastrar las cosas pesadas por el suelo; con ruedas se podían mover "
                             "mucho más fácil.",
                          [("¿Qué se hacía antes de la rueda?", "Arrastrar las cosas"),
                           ("¿Por qué es importante la rueda?", "Permite mover cosas fácilmente")])]),
    ("Antes y ahora: la casa", "Cambios en la vivienda.",
     lambda r: [b_ordenar(r, [("🕳️ Cueva", 1), ("🛖 Cabaña", 2), ("🏠 Casa", 3), ("🏢 Edificio", 4)],
                          "Numera las viviendas de la más ANTIGUA a la más MODERNA.")]),
    ("Antes y ahora: el transporte", "Evolución de los medios de transporte.",
     lambda r: [b_ordenar(r, [("🚶 A pie", 1), ("🐴 A caballo", 2),
                              ("🚂 En tren", 3), ("✈️ En avión", 4)])]),
    ("Los meses del año", "El año como ciclo largo.",
     lambda r: [b_ordenar(r, [("Enero", 1), ("Febrero", 2), ("Marzo", 3),
                              ("Abril", 4), ("Mayo", 5), ("Junio", 6)])]),
    ("El Antiguo Egipto", "Primera civilización estudiada.",
     lambda r: [b_lectura(r, "Hace miles de años, en Egipto, vivían los faraones. Construyeron "
                             "pirámides enormes de piedra que todavía existen hoy.",
                          [("¿Quién mandaba en Egipto?", "El faraón"),
                           ("¿Qué construyeron?", "Pirámides")])]),
    ("La pirámide", "Arquitectura egipcia.",
     lambda r: [b_dibujar(r, "Dibuja una pirámide con el sol detrás y un camello delante.",
                          "Mi pirámide", "mediano")]),
    ("Los jeroglíficos", "La escritura con dibujos.",
     lambda r: [b_escritura(r, [("𓂀", "EGIPTO")]),
                b_dibujar(r, "Los egipcios escribían con dibujitos. Inventa tres dibujos "
                             "para escribir tu nombre.", "Mi nombre en jeroglíficos", "mediano")]),
    ("Los oficios de antes", "Trabajos que ya casi no existen.",
     lambda r: [b_unir(r, [("Herrero", "🔨 Hacía herraduras"),
                           ("Panadero", "🍞 Hacía pan"),
                           ("Alfarero", "🏺 Hacía vasijas"),
                           ("Pastor", "🐑 Cuidaba ovejas")],
                       "Une cada oficio antiguo con lo que hacía.")]),
    ("Mi línea del tiempo", "Ordenar la propia vida.",
     lambda r: [b_ordenar(r, [("Nací", 1), ("Empecé a andar", 2),
                              ("Fui a la guardería", 3), ("Voy al cole", 4)])]),
    ("Los museos", "Dónde se guarda el pasado.",
     lambda r: [b_verdadero_falso(r, [
         ("En los museos se guardan cosas antiguas.", True),
         ("En un museo se pueden ver esqueletos de dinosaurio.", True),
         ("En los museos se pueden tocar todas las piezas.", False)])]),
    ("Repaso: viaje al pasado", "Evaluación del curso.",
     lambda r: [b_ordenar(r, [("🦕 Dinosaurios", 1), ("🔥 Prehistoria", 2),
                              ("🏜️ Antiguo Egipto", 3), ("🚗 Hoy", 4)]),
                b_verdadero_falso(r, [("Los dinosaurios vivieron antes que las personas.", True),
                                      ("Las pirámides las construyeron los dinosaurios.", False)])]),
]

CURSO_5 = [
    ("La línea del tiempo", "Representar el tiempo gráficamente.",
     lambda r: [b_ordenar(r, [("🦕 Dinosaurios", 1), ("🔥 Prehistoria", 2), ("🏜️ Egipto", 3),
                              ("🏛️ Roma", 4), ("🏰 Castillos", 5), ("🚀 Hoy", 6)])]),
    ("Egipto: el Nilo", "La geografía condiciona la civilización.",
     lambda r: [b_lectura(r, "Egipto está junto al río Nilo. Cada año el río se desbordaba y "
                             "dejaba la tierra muy fértil, así que podían cultivar trigo y verduras. "
                             "Por eso decían que Egipto era «un regalo del Nilo».",
                          [("¿Junto a qué río está Egipto?", "El Nilo"),
                           ("¿Por qué era importante que se desbordara?", "Dejaba la tierra fértil"),
                           ("¿Qué cultivaban?", "Trigo y verduras")])]),
    ("Los faraones", "La organización social egipcia.",
     lambda r: [b_verdadero_falso(r, [
         ("El faraón era el rey de Egipto.", True),
         ("Los egipcios creían que el faraón era como un dios.", True),
         ("El faraón trabajaba en el campo.", False),
         ("Tutankamón fue un faraón muy joven.", True)])]),
    ("Las pirámides", "Arquitectura funeraria.",
     lambda r: [b_lectura(r, "Las pirámides eran las tumbas de los faraones. La más grande "
                             "es la de Guiza y se construyó con más de dos millones de bloques "
                             "de piedra, colocados uno a uno.",
                          [("¿Para qué servían las pirámides?", "Eran tumbas de los faraones"),
                           ("¿Cuál es la más grande?", "La de Guiza")])]),
    ("Las momias", "Creencias sobre la muerte.",
     lambda r: [b_ordenar(r, [("Preparaban el cuerpo.", 1), ("Lo envolvían con vendas.", 2),
                              ("Lo metían en un sarcófago.", 3), ("Lo llevaban a la tumba.", 4)],
                          "Numera los pasos para hacer una momia.")]),
    ("Los jeroglíficos", "Sistemas de escritura antiguos.",
     lambda r: [b_lectura(r, "Los egipcios escribían con jeroglíficos: dibujitos que "
                             "representaban sonidos y palabras. Los escribían en papiros, "
                             "hechos con una planta del Nilo.",
                          [("¿Cómo se llama la escritura egipcia?", "Jeroglíficos"),
                           ("¿Dónde escribían?", "En papiros")])]),
    ("Los dioses de Egipto", "Politeísmo.",
     lambda r: [b_unir(r, [("Ra", "☀️ Dios del Sol"), ("Anubis", "🐕 Dios de las momias"),
                           ("Isis", "👑 Diosa madre"), ("Horus", "🦅 Dios halcón")],
                       "Une cada dios egipcio con lo que representaba.")]),
    ("La Antigua Roma", "Segunda gran civilización.",
     lambda r: [b_lectura(r, "Roma empezó siendo una ciudad pequeña en Italia y llegó a dominar "
                             "casi todo el Mediterráneo. Los romanos construyeron calzadas, "
                             "acueductos y anfiteatros.",
                          [("¿Dónde está Roma?", "En Italia"),
                           ("¿Qué construyeron los romanos?", "Calzadas, acueductos y anfiteatros")])]),
    ("El Coliseo", "Ocio y espectáculo en Roma.",
     lambda r: [b_dibujar(r, "El Coliseo era un gran edificio redondo donde luchaban los gladiadores. "
                             "Dibújalo con sus arcos.", "El Coliseo", "mediano")]),
    ("Los acueductos", "Ingeniería romana.",
     lambda r: [b_verdadero_falso(r, [
         ("Los acueductos llevaban agua a las ciudades.", True),
         ("Los romanos construían con piedra y arcos.", True),
         ("Los acueductos servían para viajar.", False)])]),
    ("Los castillos", "La Edad Media.",
     lambda r: [b_lectura(r, "En la Edad Media se construían castillos con murallas altas y "
                             "un foso alrededor. Servían para defenderse de los enemigos. "
                             "Dentro vivían los señores y sus soldados.",
                          [("¿Para qué servían los castillos?", "Para defenderse"),
                           ("¿Qué había alrededor?", "Un foso"),
                           ("¿Quién vivía dentro?", "Los señores y sus soldados")])]),
    ("Partes del castillo", "Vocabulario arquitectónico.",
     lambda r: [b_unir(r, [("Torre", "🗼 La parte más alta"), ("Muralla", "🧱 El muro que rodea"),
                           ("Foso", "💧 El agua alrededor"), ("Puente levadizo", "🌉 Se sube y se baja")],
                       "Une cada parte del castillo con lo que es.")]),
    ("Caballeros y damas", "Sociedad medieval.",
     lambda r: [b_dibujar(r, "Dibuja un caballero con su armadura y su escudo. "
                             "¡Inventa el dibujo del escudo!", "Mi caballero", "mediano")]),
    ("Los oficios medievales", "Trabajo y gremios.",
     lambda r: [b_clasificar(r, ["Oficio medieval", "Oficio de hoy"],
                             [("Herrero", 0), ("Programadora", 1), ("Juglar", 0),
                              ("Piloto", 1), ("Alfarero", 0), ("Enfermera", 1)])]),
    ("La escritura cambió el mundo", "Prehistoria frente a Historia.",
     lambda r: [b_verdadero_falso(r, [
         ("La Prehistoria es el tiempo anterior a la escritura.", True),
         ("La Historia empieza cuando se inventa la escritura.", True),
         ("En la Prehistoria escribían libros.", False)])]),
    ("Los inventos", "Relacionar invento y utilidad.",
     lambda r: [b_unir(r, [("La rueda", "🛞 Mover cosas pesadas"),
                           ("La imprenta", "📖 Hacer muchos libros"),
                           ("La bombilla", "💡 Tener luz de noche"),
                           ("El teléfono", "📞 Hablar a distancia")],
                       "Une cada invento con para qué sirve.")]),
    ("Ordena las civilizaciones", "Cronología de las grandes culturas.",
     lambda r: [b_ordenar(r, [("Prehistoria", 1), ("Antiguo Egipto", 2),
                              ("Antigua Roma", 3), ("Edad Media", 4), ("Hoy", 5)])]),
    ("Mi pueblo o ciudad", "Historia local.",
     lambda r: [b_dibujar(r, "Pregunta en casa cómo era tu calle o tu pueblo hace muchos años "
                             "y dibújalo.", "Mi pueblo antes", "mediano")]),
    ("El trabajo del arqueólogo", "Cómo se investiga el pasado.",
     lambda r: [b_lectura(r, "Los arqueólogos excavan la tierra con mucho cuidado para encontrar "
                             "restos antiguos: vasijas, monedas, huesos. Cada objeto cuenta algo "
                             "de cómo vivía la gente.",
                          [("¿Qué hacen los arqueólogos?", "Excavan para encontrar restos antiguos"),
                           ("¿Qué encuentran?", "Vasijas, monedas y huesos")])]),
    ("Repaso: grandes civilizaciones", "Evaluación del curso.",
     lambda r: [b_ordenar(r, [("🔥 Prehistoria", 1), ("🏜️ Egipto", 2),
                              ("🏛️ Roma", 3), ("🏰 Edad Media", 4)]),
                b_verdadero_falso(r, [("Las pirámides son egipcias.", True),
                                      ("El Coliseo es romano.", True),
                                      ("Los castillos son de la Edad Media.", True),
                                      ("Los romanos construyeron las pirámides.", False)])]),
]

CURSO_6 = [
    ("Las edades de la Historia", "Las grandes divisiones cronológicas.",
     lambda r: [b_ordenar(r, [("Prehistoria", 1), ("Edad Antigua", 2), ("Edad Media", 3),
                              ("Edad Moderna", 4), ("Edad Contemporánea", 5)]),
                b_verdadero_falso(r, [("La Prehistoria es la etapa más larga.", True),
                                      ("Vivimos en la Edad Contemporánea.", True),
                                      ("La Edad Media viene antes que la Edad Antigua.", False)])]),
    ("Qué es un siglo", "La unidad de medida histórica.",
     lambda r: [b_lectura(r, "Un siglo son cien años. Los historiadores los escriben con "
                             "números romanos: el siglo XX va del año 1901 al 2000, y el siglo XXI "
                             "empezó en 2001.",
                          [("¿Cuántos años tiene un siglo?", "Cien"),
                           ("¿Cómo se escriben los siglos?", "Con números romanos"),
                           ("¿En qué siglo estamos?", "En el siglo XXI")])]),
    ("Números romanos", "Leer la notación de los siglos.",
     lambda r: [b_unir(r, [("I", "1"), ("V", "5"), ("X", "10"), ("L", "50"), ("C", "100")],
                       "Une cada número romano con su valor.")]),
    ("Prehistoria: Paleolítico", "Nomadismo y caza.",
     lambda r: [b_lectura(r, "En el Paleolítico las personas eran nómadas: se movían de un sitio "
                             "a otro siguiendo a los animales. Vivían de la caza y de recoger frutos, "
                             "y usaban herramientas de piedra tallada.",
                          [("¿Qué significa nómada?", "Que se mueve de un sitio a otro"),
                           ("¿De qué vivían?", "De la caza y la recolección"),
                           ("¿De qué eran sus herramientas?", "De piedra tallada")])]),
    ("Prehistoria: Neolítico", "El gran cambio: agricultura y ganadería.",
     lambda r: [b_clasificar(r, ["Paleolítico", "Neolítico"],
                             [("Cazar y recolectar", 0), ("Cultivar la tierra", 1),
                              ("Ser nómada", 0), ("Vivir en poblados", 1),
                              ("Piedra tallada", 0), ("Piedra pulida", 1)])]),
    ("Egipto: la sociedad", "Estructura piramidal de la sociedad.",
     lambda r: [b_ordenar(r, [("Faraón", 1), ("Sacerdotes y nobles", 2),
                              ("Escribas y artesanos", 3), ("Campesinos", 4), ("Esclavos", 5)],
                          "Ordena la sociedad egipcia del que más mandaba al que menos.")]),
    ("Grecia: la cuna de la democracia", "Aportación política griega.",
     lambda r: [b_lectura(r, "En Atenas, hace unos 2.500 años, se inventó la democracia: "
                             "los ciudadanos se reunían para votar las decisiones importantes. "
                             "También inventaron el teatro y los Juegos Olímpicos.",
                          [("¿Dónde se inventó la democracia?", "En Atenas"),
                           ("¿Qué es la democracia?", "Que los ciudadanos voten las decisiones"),
                           ("¿Qué más inventaron los griegos?", "El teatro y los Juegos Olímpicos")])]),
    ("Los Juegos Olímpicos", "Del pasado al presente.",
     lambda r: [b_verdadero_falso(r, [
         ("Los Juegos Olímpicos nacieron en Grecia.", True),
         ("Se celebran cada cuatro años.", True),
         ("Los inventaron los romanos.", False)])]),
    ("Roma: de república a imperio", "Evolución política romana.",
     lambda r: [b_ordenar(r, [("Roma es una ciudad pequeña.", 1),
                              ("Se convierte en república.", 2),
                              ("Conquista el Mediterráneo.", 3),
                              ("Se convierte en imperio.", 4),
                              ("El imperio cae.", 5)])]),
    ("La herencia romana", "Lo que nos dejaron los romanos.",
     lambda r: [b_clasificar(r, ["Nos lo dejaron los romanos", "No es romano"],
                             [("El latín", 0), ("Los acueductos", 0), ("Internet", 1),
                              ("Las calzadas", 0), ("El alfabeto latino", 0), ("El avión", 1)])]),
    ("La Edad Media: el feudalismo", "Organización social medieval.",
     lambda r: [b_lectura(r, "En la Edad Media, los reyes daban tierras a los nobles a cambio de "
                             "que les ayudaran en la guerra. Los campesinos trabajaban esas tierras "
                             "y entregaban parte de la cosecha al señor.",
                          [("¿Qué daban los reyes a los nobles?", "Tierras"),
                           ("¿Qué recibían a cambio?", "Ayuda en la guerra"),
                           ("¿Qué hacían los campesinos?", "Trabajaban la tierra y pagaban al señor")])]),
    ("Los monasterios", "La cultura en la Edad Media.",
     lambda r: [b_verdadero_falso(r, [
         ("En los monasterios se copiaban libros a mano.", True),
         ("Los monjes conservaron muchos textos antiguos.", True),
         ("En la Edad Media todo el mundo sabía leer.", False)])]),
    ("El descubrimiento de América", "1492 y la Edad Moderna.",
     lambda r: [b_lectura(r, "En 1492, Cristóbal Colón salió del puerto de Palos con tres naves: "
                             "la Niña, la Pinta y la Santa María. Buscaba llegar a Asia por el oeste "
                             "y llegó a América sin saberlo.",
                          [("¿En qué año fue?", "En 1492"),
                           ("¿Cómo se llamaban las naves?", "La Niña, la Pinta y la Santa María"),
                           ("¿Qué buscaba Colón?", "Llegar a Asia por el oeste")])]),
    ("La imprenta", "Un invento que difundió el saber.",
     lambda r: [b_lectura(r, "Antes de la imprenta, cada libro se copiaba a mano y tardaba meses. "
                             "Gutenberg inventó la imprenta hacia 1450 y desde entonces se pudieron "
                             "hacer muchos libros iguales muy deprisa.",
                          [("¿Cómo se hacían los libros antes?", "A mano, uno a uno"),
                           ("¿Quién inventó la imprenta?", "Gutenberg")])]),
    ("Ordena por siglos", "Situar hechos en el tiempo.",
     lambda r: [b_ordenar(r, [("Se construyen las pirámides", 1),
                              ("Nace la democracia en Atenas", 2),
                              ("Cae el Imperio Romano", 3),
                              ("Colón llega a América", 4),
                              ("Se inventa el ordenador", 5)])]),
    ("Los inventos y su siglo", "Cronología de la técnica.",
     lambda r: [b_unir(r, [("Imprenta", "Siglo XV"), ("Máquina de vapor", "Siglo XVIII"),
                           ("Bombilla", "Siglo XIX"), ("Internet", "Siglo XX")],
                       "Une cada invento con el siglo en el que apareció.")]),
    ("Fuentes históricas", "Cómo se conoce el pasado.",
     lambda r: [b_clasificar(r, ["Fuente escrita", "Fuente material"],
                             [("Un libro antiguo", 0), ("Una vasija", 1), ("Una carta", 0),
                              ("Una moneda", 1), ("Un periódico viejo", 0), ("Una espada", 1)])]),
    ("Mi línea del tiempo familiar", "Aplicar la cronología a lo cercano.",
     lambda r: [b_dibujar(r, "Pregunta en casa el año en que nacieron tus abuelos, tus padres y tú. "
                             "Dibuja una línea del tiempo con los tres momentos.",
                          "Mi familia en el tiempo", "mediano")]),
    ("El patrimonio", "Conservar lo heredado.",
     lambda r: [b_verdadero_falso(r, [
         ("El patrimonio son los bienes históricos que heredamos.", True),
         ("Cuidar los monumentos es responsabilidad de todos.", True),
         ("Se puede pintar en un monumento antiguo.", False)])]),
    ("Repaso: de la Prehistoria a hoy", "Evaluación del curso.",
     lambda r: [b_ordenar(r, [("Paleolítico", 1), ("Neolítico", 2), ("Egipto y Grecia", 3),
                              ("Roma", 4), ("Edad Media", 5), ("Hoy", 6)]),
                b_verdadero_falso(r, [("Un siglo son cien años.", True),
                                      ("Colón llegó a América en 1492.", True),
                                      ("La democracia nació en Roma.", False)])]),
]

CURSO_7 = [
    ("Repaso: las edades de la Historia", "Consolidar la cronología general.",
     lambda r: [b_ordenar(r, [("Prehistoria", 1), ("Edad Antigua", 2), ("Edad Media", 3),
                              ("Edad Moderna", 4), ("Edad Contemporánea", 5)]),
                b_unir(r, [("Prehistoria", "Antes de la escritura"),
                           ("Edad Antigua", "Egipto, Grecia y Roma"),
                           ("Edad Media", "Castillos y feudalismo"),
                           ("Edad Moderna", "Desde 1492"),
                           ("Edad Contemporánea", "Desde 1789 hasta hoy")],
                       "Une cada edad con lo que la caracteriza.")]),
    ("Antes y después de Cristo", "El sistema de datación.",
     lambda r: [b_lectura(r, "Contamos los años a partir del nacimiento de Cristo. Los años "
                             "anteriores se escriben «a. C.» y van hacia atrás: el año 200 a. C. "
                             "es anterior al 100 a. C. Los posteriores son «d. C.» y van hacia delante.",
                          [("¿Qué significa a. C.?", "Antes de Cristo"),
                           ("¿Qué año es anterior, el 200 a.C. o el 100 a.C.?", "El 200 a. C."),
                           ("¿En qué dirección van los años d. C.?", "Hacia delante")])]),
    ("Mesopotamia", "La primera escritura.",
     lambda r: [b_lectura(r, "En Mesopotamia, entre los ríos Tigris y Éufrates, se inventó la "
                             "escritura cuneiforme hacia el año 3300 a. C. Escribían sobre tablillas "
                             "de barro con una caña. Con la escritura empieza la Historia.",
                          [("¿Entre qué ríos estaba Mesopotamia?", "El Tigris y el Éufrates"),
                           ("¿Cómo se llamaba su escritura?", "Cuneiforme"),
                           ("¿Sobre qué escribían?", "Tablillas de barro")])]),
    ("Grecia: Atenas y Esparta", "Dos modelos de ciudad-estado.",
     lambda r: [b_clasificar(r, ["Atenas", "Esparta"],
                             [("La democracia", 0), ("El ejército", 1), ("La filosofía", 0),
                              ("El entrenamiento militar", 1), ("El teatro", 0)])]),
    ("Los filósofos griegos", "El pensamiento clásico.",
     lambda r: [b_unir(r, [("Sócrates", "Enseñaba preguntando"),
                           ("Platón", "Fundó la Academia"),
                           ("Aristóteles", "Estudió la naturaleza"),
                           ("Pitágoras", "El teorema de los triángulos")],
                       "Une cada filósofo con aquello por lo que se le recuerda.")]),
    ("Roma: la vida cotidiana", "Sociedad y costumbres romanas.",
     lambda r: [b_lectura(r, "Los romanos vivían en casas llamadas «domus» si eran ricos, o en "
                             "bloques de pisos llamados «insulae» si eran pobres. Se bañaban en las "
                             "termas públicas y compraban en el foro, la plaza principal.",
                          [("¿Cómo se llamaba la casa de los ricos?", "Domus"),
                           ("¿Y los bloques de pisos?", "Insulae"),
                           ("¿Dónde se bañaban?", "En las termas"),
                           ("¿Qué era el foro?", "La plaza principal")])]),
    ("La caída del Imperio Romano", "Un final que abre una etapa.",
     lambda r: [b_verdadero_falso(r, [
         ("El Imperio Romano de Occidente cayó en el año 476.", True),
         ("Con su caída empieza la Edad Media.", True),
         ("El imperio cayó en un solo día.", False),
         ("Los pueblos germanos invadieron el imperio.", True)])]),
    ("Al-Ándalus", "La presencia musulmana en la península.",
     lambda r: [b_lectura(r, "Durante casi ocho siglos, buena parte de la península ibérica fue "
                             "Al-Ándalus. Córdoba llegó a ser una de las ciudades más grandes y "
                             "cultas de Europa, con bibliotecas y baños públicos.",
                          [("¿Cuánto duró Al-Ándalus?", "Casi ocho siglos"),
                           ("¿Qué ciudad destacó?", "Córdoba"),
                           ("¿Por qué era importante?", "Era grande y culta, con bibliotecas")])]),
    ("Los tres reinos culturales", "Convivencia en la Edad Media peninsular.",
     lambda r: [b_verdadero_falso(r, [
         ("En la península convivieron cristianos, musulmanes y judíos.", True),
         ("La Alhambra de Granada es de arte musulmán.", True),
         ("Todos hablaban el mismo idioma.", False)])]),
    ("Los descubrimientos", "La expansión de la Edad Moderna.",
     lambda r: [b_ordenar(r, [("Colón llega a América (1492)", 1),
                              ("Magallanes inicia la vuelta al mundo (1519)", 2),
                              ("Elcano la completa (1522)", 3)])]),
    ("La imprenta y la ciencia", "Difusión del conocimiento.",
     lambda r: [b_lectura(r, "Gracias a la imprenta, las ideas viajaban deprisa. Científicos como "
                             "Copérnico y Galileo pudieron publicar que la Tierra gira alrededor "
                             "del Sol, y no al revés como se creía.",
                          [("¿Qué permitió la imprenta?", "Que las ideas viajaran deprisa"),
                           ("¿Qué descubrieron Copérnico y Galileo?", "Que la Tierra gira alrededor del Sol")])]),
    ("La Revolución Industrial", "El gran cambio del siglo XVIII.",
     lambda r: [b_lectura(r, "En el siglo XVIII se inventó la máquina de vapor. Aparecieron las "
                             "fábricas y mucha gente se mudó del campo a la ciudad para trabajar "
                             "en ellas. Las ciudades crecieron muchísimo.",
                          [("¿Qué máquina fue clave?", "La máquina de vapor"),
                           ("¿Adónde se mudó la gente?", "Del campo a la ciudad"),
                           ("¿Por qué?", "Para trabajar en las fábricas")])]),
    ("Inventos del siglo XIX", "Técnica y vida cotidiana.",
     lambda r: [b_unir(r, [("Tren de vapor", "Viajar por tierra más rápido"),
                           ("Telégrafo", "Enviar mensajes a distancia"),
                           ("Bombilla", "Iluminar sin fuego"),
                           ("Fotografía", "Guardar imágenes reales")],
                       "Une cada invento del siglo XIX con lo que permitió hacer.")]),
    ("El siglo XX", "Un siglo de cambios acelerados.",
     lambda r: [b_ordenar(r, [("Primer vuelo de los hermanos Wright (1903)", 1),
                              ("Primera televisión (años 20)", 2),
                              ("Llegada a la Luna (1969)", 3),
                              ("Internet se populariza (años 90)", 4)])]),
    ("La llegada a la Luna", "Un hito de la exploración.",
     lambda r: [b_lectura(r, "El 20 de julio de 1969, la nave Apolo 11 llegó a la Luna. "
                             "Neil Armstrong fue el primer ser humano en pisarla y dijo que era "
                             "«un pequeño paso para el hombre, un gran salto para la humanidad».",
                          [("¿En qué año llegaron a la Luna?", "En 1969"),
                           ("¿Cómo se llamaba la nave?", "Apolo 11"),
                           ("¿Quién pisó la Luna primero?", "Neil Armstrong")])]),
    ("Trabajar con fuentes", "Método histórico.",
     lambda r: [b_clasificar(r, ["Fuente primaria", "Fuente secundaria"],
                             [("Una carta de la época", 0), ("Un libro de texto de hoy", 1),
                              ("Una moneda romana", 0), ("Un documental actual", 1),
                              ("Un diario personal antiguo", 0)])]),
    ("¿En qué siglo ocurrió?", "Convertir años en siglos.",
     lambda r: [b_unir(r, [("1492", "Siglo XV"), ("1789", "Siglo XVIII"),
                           ("1969", "Siglo XX"), ("2020", "Siglo XXI")],
                       "Une cada año con su siglo.")]),
    ("El patrimonio de mi entorno", "Historia local e investigación.",
     lambda r: [b_dibujar(r, "Busca un edificio antiguo de tu pueblo o ciudad. Dibújalo y escribe "
                             "debajo qué es y de cuándo crees que es.", "Patrimonio cercano", "mediano")]),
    ("Causas y consecuencias", "Pensamiento causal en historia.",
     lambda r: [b_unir(r, [("Se inventa la agricultura", "La gente deja de ser nómada"),
                           ("Se inventa la imprenta", "Los libros se hacen más baratos"),
                           ("Se inventa la máquina de vapor", "Nacen las fábricas"),
                           ("Se inventa internet", "La información viaja al instante")],
                       "Une cada causa con su consecuencia.")]),
    ("Repaso final", "Evaluación global del curso.",
     lambda r: [b_ordenar(r, [("Se inventa la escritura", 1), ("Cae el Imperio Romano", 2),
                              ("Colón llega a América", 3), ("Revolución Industrial", 4),
                              ("Llegada a la Luna", 5)]),
                b_verdadero_falso(r, [("La Historia empieza con la escritura.", True),
                                      ("El siglo XX va de 1901 a 2000.", True),
                                      ("La Edad Media termina en 1492.", True),
                                      ("Los romanos inventaron la imprenta.", False)])]),
]

CURRICULO = {2: CURSO_2, 3: CURSO_3, 4: CURSO_4, 5: CURSO_5, 6: CURSO_6, 7: CURSO_7}
