# -*- coding: utf-8 -*-
"""
Curriculo de Idiomas (ingles): 20 fichas por curso, dificultad creciente.

Progresion: del vocabulario oral con apoyo de imagen (2 anos) a las frases
completas y las preguntas basicas (7 anos). En Infantil el ingles entra por el
oido y el dibujo, no por la lectura: las fichas de 2 a 4 anos son de senalar,
colorear y unir, y la escritura aparece a partir de los 5.
"""

from generar_fichas import b_colorear, b_concepto, b_contar, b_emparejar, b_trazo, b_unir
from bloques_texto import (
    b_clasificar, b_colorear_ingles, b_completar, b_dibujar, b_escritura,
    b_frase, b_lectura, b_ordenar, b_verdadero_falso, b_vocabulario,
)


CURSO_2 = [
    ("Hello!", "Primer saludo en inglés.",
     lambda r: [b_vocabulario(r, [("👋", "HELLO", "Hola")],
                              "Saluda diciendo HELLO y colorea la mano.")]),
    ("Red", "El primer color en inglés.",
     lambda r: [b_colorear_ingles(r, [("circulo", "RED", "rojo")],
                                  "Colorea el círculo de RED (rojo).")]),
    ("Blue", "Segundo color.",
     lambda r: [b_colorear_ingles(r, [("circulo", "BLUE", "azul")],
                                  "Colorea el círculo de BLUE (azul).")]),
    ("Yellow", "Tercer color.",
     lambda r: [b_colorear_ingles(r, [("circulo", "YELLOW", "amarillo")],
                                  "Colorea el círculo de YELLOW (amarillo).")]),
    ("Dog", "Primer animal en inglés.",
     lambda r: [b_vocabulario(r, [("🐶", "DOG", "Perro")], "Di DOG en voz alta y colorea el perro.")]),
    ("Cat", "Segundo animal.",
     lambda r: [b_vocabulario(r, [("🐱", "CAT", "Gato")], "Di CAT en voz alta y colorea el gato.")]),
    ("One, two", "Los dos primeros números.",
     lambda r: [b_contar(r, 2, 2), b_vocabulario(r, [("1️⃣", "ONE", "Uno"), ("2️⃣", "TWO", "Dos")])]),
    ("Green", "Cuarto color.",
     lambda r: [b_colorear_ingles(r, [("circulo", "GREEN", "verde")],
                                  "Colorea el círculo de GREEN (verde).")]),
    ("Fish", "Vocabulario animal.",
     lambda r: [b_vocabulario(r, [("🐟", "FISH", "Pez")], "Di FISH y colorea el pez.")]),
    ("Bye bye!", "Despedida en inglés.",
     lambda r: [b_vocabulario(r, [("👋", "BYE", "Adiós")], "Di BYE BYE y saluda con la mano.")]),
    ("Big and small", "Conceptos de tamaño.",
     lambda r: [b_concepto(r, [("🐘", "big"), ("🐭", "small"), ("🌳", "big")],
                           "Rodea lo que es BIG (grande).")]),
    ("Three", "Tercer número.",
     lambda r: [b_contar(r, 2, 3), b_vocabulario(r, [("3️⃣", "THREE", "Tres")])]),
    ("Bird", "Vocabulario animal.",
     lambda r: [b_vocabulario(r, [("🐦", "BIRD", "Pájaro")], "Di BIRD y colorea el pájaro.")]),
    ("Sun and moon", "Vocabulario del cielo.",
     lambda r: [b_vocabulario(r, [("☀️", "SUN", "Sol"), ("🌙", "MOON", "Luna")])]),
    ("Find the same", "Discriminación visual con vocabulario.",
     lambda r: [b_emparejar(r, 3)]),
    ("Mum and Dad", "Vocabulario familiar.",
     lambda r: [b_vocabulario(r, [("👩", "MUM", "Mamá"), ("👨", "DAD", "Papá")])]),
    ("Apple", "Primera palabra de comida.",
     lambda r: [b_vocabulario(r, [("🍎", "APPLE", "Manzana")], "Di APPLE y colorea la manzana de RED.")]),
    ("Water", "Vocabulario básico.",
     lambda r: [b_vocabulario(r, [("💧", "WATER", "Agua")])]),
    ("My colours", "Repaso de los cuatro colores.",
     lambda r: [b_colorear_ingles(r, [("circulo", "RED", "rojo"), ("cuadrado", "BLUE", "azul"),
                                      ("triangulo", "YELLOW", "amarillo"), ("ovalo", "GREEN", "verde")])]),
    ("Repaso: my first words", "Consolidar el vocabulario del curso.",
     lambda r: [b_unir(r, [("🐶", "DOG"), ("🐱", "CAT"), ("☀️", "SUN"), ("🍎", "APPLE")],
                       "Une cada dibujo con su palabra en inglés.")]),
]

CURSO_3 = [
    ("Colours: red and blue", "Consolidar los dos primeros colores.",
     lambda r: [b_colorear_ingles(r, [("circulo", "RED", "rojo"), ("cuadrado", "BLUE", "azul")])]),
    ("Colours: yellow and green", "Ampliar la paleta.",
     lambda r: [b_colorear_ingles(r, [("triangulo", "YELLOW", "amarillo"), ("ovalo", "GREEN", "verde")])]),
    ("Numbers 1 to 3", "Los tres primeros números.",
     lambda r: [b_vocabulario(r, [("1️⃣", "ONE", "Uno"), ("2️⃣", "TWO", "Dos"), ("3️⃣", "THREE", "Tres")]),
                b_contar(r, 3, 3)]),
    ("Numbers 4 and 5", "Ampliar hasta cinco.",
     lambda r: [b_vocabulario(r, [("4️⃣", "FOUR", "Cuatro"), ("5️⃣", "FIVE", "Cinco")]),
                b_contar(r, 3, 5)]),
    ("Farm animals", "Vocabulario de la granja.",
     lambda r: [b_unir(r, [("🐮", "COW"), ("🐷", "PIG"), ("🐔", "HEN"), ("🐴", "HORSE")],
                       "Une cada animal de la granja con su nombre en inglés.")]),
    ("Pet animals", "Animales de compañía.",
     lambda r: [b_unir(r, [("🐶", "DOG"), ("🐱", "CAT"), ("🐟", "FISH"), ("🐰", "RABBIT")],
                       "Une cada mascota con su nombre en inglés.")]),
    ("Big and small", "Adjetivos de tamaño.",
     lambda r: [b_clasificar(r, ["BIG", "SMALL"],
                             [("🐘", 0), ("🐜", 1), ("🐳", 0), ("🐭", 1), ("🦒", 0), ("🐞", 1)])]),
    ("My family", "Vocabulario familiar.",
     lambda r: [b_vocabulario(r, [("👩", "MUM", "Mamá"), ("👨", "DAD", "Papá"),
                                  ("👶", "BABY", "Bebé")]),
                b_dibujar(r, "Draw your family. Dibuja a tu familia.", "My family", "mediano")]),
    ("Fruit", "Vocabulario de frutas.",
     lambda r: [b_unir(r, [("🍎", "APPLE"), ("🍌", "BANANA"), ("🍇", "GRAPES"), ("🍊", "ORANGE")],
                       "Une cada fruta con su nombre en inglés.")]),
    ("Orange and purple", "Dos colores nuevos.",
     lambda r: [b_colorear_ingles(r, [("circulo", "ORANGE", "naranja"), ("cuadrado", "PURPLE", "morado")])]),
    ("Count in English", "Contar en inglés hasta cinco.",
     lambda r: [b_contar(r, 4, 5),
                b_unir(r, [("1", "ONE"), ("2", "TWO"), ("3", "THREE"), ("4", "FOUR"), ("5", "FIVE")],
                       "Une cada número con su palabra en inglés.")]),
    ("The sun and the moon", "Vocabulario del cielo y del tiempo.",
     lambda r: [b_vocabulario(r, [("☀️", "SUN", "Sol"), ("🌙", "MOON", "Luna"),
                                  ("⭐", "STAR", "Estrella")])]),
    ("Wild animals", "Animales salvajes.",
     lambda r: [b_unir(r, [("🦁", "LION"), ("🐘", "ELEPHANT"), ("🐒", "MONKEY"), ("🐻", "BEAR")],
                       "Une cada animal salvaje con su nombre en inglés.")]),
    ("Hello and goodbye", "Fórmulas de saludo.",
     lambda r: [b_vocabulario(r, [("👋", "HELLO", "Hola"), ("👋", "GOODBYE", "Adiós"),
                                  ("🙏", "PLEASE", "Por favor")])]),
    ("Classify: animals and fruit", "Categorías semánticas en inglés.",
     lambda r: [b_clasificar(r, ["ANIMALS", "FRUIT"],
                             [("DOG", 0), ("APPLE", 1), ("CAT", 0),
                              ("BANANA", 1), ("FISH", 0), ("ORANGE", 1)])]),
    ("Toys", "Vocabulario de juguetes.",
     lambda r: [b_unir(r, [("⚽", "BALL"), ("🧸", "TEDDY"), ("🚗", "CAR"), ("🪁", "KITE")],
                       "Une cada juguete con su nombre en inglés.")]),
    ("Black and white", "Colores acromáticos.",
     lambda r: [b_colorear_ingles(r, [("circulo", "BLACK", "negro"), ("cuadrado", "WHITE", "blanco")])]),
    ("My favourite colour", "Expresión personal.",
     lambda r: [b_dibujar(r, "Draw something of your favourite colour. Dibuja algo de tu color "
                             "favorito y escribe su nombre en inglés.", "My colour", "mediano")]),
    ("Listen and point", "Comprensión oral guiada por un adulto.",
     lambda r: [b_emparejar(r, 4)]),
    ("Repaso: colours, numbers, animals", "Evaluación del curso.",
     lambda r: [b_unir(r, [("🔴", "RED"), ("3️⃣", "THREE"), ("🐶", "DOG"), ("🍎", "APPLE")],
                       "Une cada dibujo con su palabra en inglés.")]),
]

CURSO_4 = [
    ("Numbers 1 to 10", "Ampliar la serie numérica en inglés.",
     lambda r: [b_unir(r, [("6", "SIX"), ("7", "SEVEN"), ("8", "EIGHT"),
                           ("9", "NINE"), ("10", "TEN")],
                       "Une cada número con su palabra en inglés.")]),
    ("Trace the numbers", "Grafía de los numerales ingleses.",
     lambda r: [b_trazo(r, ["ONE", "TWO", "THREE"], 3),
                b_trazo(r, ["FOUR", "FIVE"], 3)]),
    ("My body", "Partes del cuerpo.",
     lambda r: [b_unir(r, [("👁️", "EYE"), ("👃", "NOSE"), ("👄", "MOUTH"),
                           ("👂", "EAR"), ("✋", "HAND")],
                       "Une cada parte del cuerpo con su nombre en inglés.")]),
    ("Draw a face", "Aplicar el vocabulario del cuerpo.",
     lambda r: [b_dibujar(r, "Draw a face with two eyes, one nose and one mouth. "
                             "Escribe el nombre de cada parte en inglés.", "My face", "mediano")]),
    ("Food", "Vocabulario de comida.",
     lambda r: [b_vocabulario(r, [("🍞", "BREAD", "Pan"), ("🥛", "MILK", "Leche"),
                                  ("🧀", "CHEESE", "Queso"), ("🥚", "EGG", "Huevo")])]),
    ("The family", "Ampliar el vocabulario familiar.",
     lambda r: [b_unir(r, [("👩", "MOTHER"), ("👨", "FATHER"), ("👦", "BROTHER"),
                           ("👧", "SISTER"), ("👵", "GRANDMOTHER")],
                       "Une cada persona con su palabra en inglés.")]),
    ("Colours review", "Repaso de la paleta completa.",
     lambda r: [b_colorear_ingles(r, [("circulo", "RED", "rojo"), ("cuadrado", "BLUE", "azul"),
                                      ("triangulo", "GREEN", "verde"), ("ovalo", "YELLOW", "amarillo")])]),
    ("My house", "Vocabulario del hogar.",
     lambda r: [b_unir(r, [("🚪", "DOOR"), ("🪟", "WINDOW"), ("🛏️", "BED"),
                           ("🪑", "CHAIR"), ("🍽️", "TABLE")],
                       "Une cada objeto de la casa con su nombre en inglés.")]),
    ("Classroom objects", "Vocabulario escolar.",
     lambda r: [b_vocabulario(r, [("✏️", "PENCIL", "Lápiz"), ("📕", "BOOK", "Libro"),
                                  ("🎒", "BAG", "Mochila"), ("✂️", "SCISSORS", "Tijeras")])]),
    ("The missing letter", "Escritura de palabras inglesas.",
     lambda r: [b_completar(r, [("🐶", "DOG", 1), ("🐱", "CAT", 0),
                                ("☀️", "SUN", 2), ("🐟", "FISH", 1)])]),
    ("Count and write", "Contar y escribir el numeral inglés.",
     lambda r: [b_contar(r, 4, 10)]),
    ("Clothes", "Vocabulario de ropa.",
     lambda r: [b_unir(r, [("👕", "T-SHIRT"), ("👖", "TROUSERS"), ("👟", "SHOES"), ("🧢", "CAP")],
                       "Une cada prenda con su nombre en inglés.")]),
    ("Classify: food and clothes", "Categorías en inglés.",
     lambda r: [b_clasificar(r, ["FOOD", "CLOTHES"],
                             [("BREAD", 0), ("SHOES", 1), ("MILK", 0),
                              ("T-SHIRT", 1), ("APPLE", 0), ("CAP", 1)])]),
    ("Yes and no", "Respuestas básicas.",
     lambda r: [b_verdadero_falso(r, [("A DOG is an animal.", True),
                                      ("An APPLE is a colour.", False),
                                      ("BLUE is a colour.", True),
                                      ("A CHAIR is food.", False)])]),
    ("Numbers 11 to 15", "Ampliar más allá de diez.",
     lambda r: [b_unir(r, [("11", "ELEVEN"), ("12", "TWELVE"), ("13", "THIRTEEN"),
                           ("14", "FOURTEEN"), ("15", "FIFTEEN")],
                       "Une cada número con su palabra en inglés.")]),
    ("Weather", "Vocabulario del tiempo atmosférico.",
     lambda r: [b_vocabulario(r, [("☀️", "SUNNY", "Soleado"), ("🌧️", "RAINY", "Lluvioso"),
                                  ("☁️", "CLOUDY", "Nublado")])]),
    ("Sea animals", "Animales marinos.",
     lambda r: [b_unir(r, [("🐠", "FISH"), ("🐙", "OCTOPUS"), ("🦈", "SHARK"), ("🐢", "TURTLE")],
                       "Une cada animal marino con su nombre en inglés.")]),
    ("Write the words", "Escritura de vocabulario conocido.",
     lambda r: [b_escritura(r, [("🐶", "DOG"), ("☀️", "SUN"), ("🍎", "APPLE")],
                            "Trace the word and write it again. Repasa y escribe.")]),
    ("My favourite animal", "Producción personal.",
     lambda r: [b_dibujar(r, "Draw your favourite animal and write its name in English. "
                             "Dibuja tu animal favorito y escribe su nombre en inglés.",
                          "My favourite animal", "mediano")]),
    ("Repaso: my English words", "Evaluación del curso.",
     lambda r: [b_unir(r, [("👁️", "EYE"), ("🍞", "BREAD"), ("👕", "T-SHIRT"), ("🪟", "WINDOW")],
                       "Une cada dibujo con su palabra en inglés."),
                b_completar(r, [("🥛", "MILK", 2), ("📕", "BOOK", 1)])]),
]

CURSO_5 = [
    ("Greetings", "Fórmulas sociales según el momento del día.",
     lambda r: [b_vocabulario(r, [("🌅", "GOOD MORNING", "Buenos días"),
                                  ("🌇", "GOOD AFTERNOON", "Buenas tardes"),
                                  ("🌙", "GOOD NIGHT", "Buenas noches")])]),
    ("What's your name?", "Presentarse.",
     lambda r: [b_frase(r, [("MY NAME ", "IS", " ANNA."), ("HELLO, I ", "AM", " TOM.")],
                        "Completa cada frase con IS o AM.")]),
    ("Numbers 1 to 20", "Serie numérica ampliada.",
     lambda r: [b_unir(r, [("16", "SIXTEEN"), ("17", "SEVENTEEN"), ("18", "EIGHTEEN"),
                           ("19", "NINETEEN"), ("20", "TWENTY")],
                       "Une cada número con su palabra en inglés.")]),
    ("Days of the week", "Los siete días.",
     lambda r: [b_ordenar(r, [("MONDAY", 1), ("TUESDAY", 2), ("WEDNESDAY", 3), ("THURSDAY", 4),
                              ("FRIDAY", 5), ("SATURDAY", 6), ("SUNDAY", 7)],
                          "Order the days of the week. Ordénalos del 1 al 7.")]),
    ("The body", "Ampliar el vocabulario corporal.",
     lambda r: [b_unir(r, [("🦵", "LEG"), ("💪", "ARM"), ("🦶", "FOOT"),
                           ("🖐️", "FINGER"), ("👤", "HEAD")],
                       "Une cada parte del cuerpo con su nombre en inglés.")]),
    ("I like / I don't like", "Expresar preferencias.",
     lambda r: [b_frase(r, [("I ", "LIKE", " CHOCOLATE."), ("I DON'T ", "LIKE", " ONIONS.")],
                        "Completa las frases con LIKE.")]),
    ("Clothes and weather", "Relacionar dos campos semánticos.",
     lambda r: [b_unir(r, [("☀️ SUNNY", "🕶️ SUNGLASSES"), ("🌧️ RAINY", "☂️ UMBRELLA"),
                           ("❄️ SNOWY", "🧣 SCARF"), ("💨 WINDY", "🧥 COAT")],
                       "Une cada tiempo con la ropa adecuada.")]),
    ("This is a...", "Estructura de identificación.",
     lambda r: [b_frase(r, [("THIS IS A ", "DOG", "."), ("THIS IS AN ", "APPLE", ".")],
                        "Completa con la palabra correcta. Fíjate: A o AN.")]),
    ("A or AN?", "Regla del artículo indeterminado.",
     lambda r: [b_clasificar(r, ["A", "AN"],
                             [("DOG", 0), ("APPLE", 1), ("CAT", 0),
                              ("ORANGE", 1), ("BOOK", 0), ("EGG", 1)]),
                b_verdadero_falso(r, [("AN se usa delante de vocal.", True),
                                      ("Se dice «a apple».", False)])]),
    ("Colours and shapes", "Combinar dos campos.",
     lambda r: [b_colorear_ingles(r, [("circulo", "RED", "rojo"), ("cuadrado", "BLUE", "azul"),
                                      ("triangulo", "GREEN", "verde"), ("rombo", "PINK", "rosa")])]),
    ("My school", "Vocabulario escolar ampliado.",
     lambda r: [b_vocabulario(r, [("👩‍🏫", "TEACHER", "Profesora"), ("🧒", "PUPIL", "Alumno"),
                                  ("🏫", "SCHOOL", "Colegio"), ("📝", "HOMEWORK", "Deberes")])]),
    ("Numbers: how many?", "Preguntar por cantidad.",
     lambda r: [b_contar(r, 4, 10),
                b_frase(r, [("HOW ", "MANY", " APPLES?")], "Completa la pregunta.")]),
    ("Food and drink", "Ampliar comida y bebida.",
     lambda r: [b_clasificar(r, ["FOOD", "DRINK"],
                             [("BREAD", 0), ("WATER", 1), ("CHEESE", 0),
                              ("MILK", 1), ("APPLE", 0), ("JUICE", 1)])]),
    ("Where is it?", "Preposiciones de lugar.",
     lambda r: [b_unir(r, [("IN", "Dentro"), ("ON", "Encima"), ("UNDER", "Debajo"), ("NEXT TO", "Al lado")],
                       "Une cada preposición con su significado.")]),
    ("Read and draw", "Comprensión lectora básica en inglés.",
     lambda r: [b_dibujar(r, "Read and draw: «A big yellow sun and three small blue fish.» "
                             "Dibuja lo que dice la frase.", "Read and draw", "mediano")]),
    ("Write the words", "Escritura autónoma.",
     lambda r: [b_escritura(r, [("🏫", "SCHOOL"), ("👩‍🏫", "TEACHER"), ("📕", "BOOK")],
                            "Trace and write. Repasa y escribe cada palabra.")]),
    ("The missing letter", "Ortografía inglesa.",
     lambda r: [b_completar(r, [("🏫", "SCHOOL", 2), ("🐴", "HORSE", 1),
                                ("🥛", "MILK", 3), ("🪟", "WINDOW", 4)])]),
    ("True or false", "Comprensión con vocabulario acumulado.",
     lambda r: [b_verdadero_falso(r, [
         ("MONDAY is a day of the week.", True),
         ("A TEACHER works at school.", True),
         ("GREEN is a number.", False),
         ("An ELEPHANT is small.", False)])]),
    ("My favourite day", "Producción personal escrita.",
     lambda r: [b_dibujar(r, "What is your favourite day? Draw it and write: "
                             "«My favourite day is ______.»", "My favourite day", "mediano")]),
    ("Repaso: I can speak English", "Evaluación del curso.",
     lambda r: [b_frase(r, [("MY NAME ", "IS", " ..."), ("I ", "LIKE", " ...")]),
                b_unir(r, [("MONDAY", "Lunes"), ("TEACHER", "Profesora"),
                           ("UNDER", "Debajo"), ("MILK", "Leche")],
                       "Une cada palabra con su significado.")]),
]

CURSO_6 = [
    ("The verb TO BE", "El verbo más importante del inglés.",
     lambda r: [b_frase(r, [("I ", "AM", " a pupil."), ("YOU ", "ARE", " my friend."),
                            ("HE ", "IS", " my brother.")],
                        "Completa con AM, ARE o IS.")]),
    ("I am / You are / He is", "Conjugación completa.",
     lambda r: [b_unir(r, [("I", "AM"), ("YOU", "ARE"), ("HE / SHE / IT", "IS"),
                           ("WE", "ARE"), ("THEY", "ARE")],
                       "Une cada pronombre con su forma del verbo TO BE.")]),
    ("Questions with TO BE", "Formular preguntas.",
     lambda r: [b_frase(r, [("", "ARE", " you happy?"), ("", "IS", " she your sister?")],
                        "Completa las preguntas con ARE o IS.")]),
    ("Months of the year", "Los doce meses.",
     lambda r: [b_ordenar(r, [("JANUARY", 1), ("FEBRUARY", 2), ("MARCH", 3),
                              ("APRIL", 4), ("MAY", 5), ("JUNE", 6)],
                          "Order the months from 1 to 6.")]),
    ("Months: July to December", "Segunda mitad del año.",
     lambda r: [b_ordenar(r, [("JULY", 1), ("AUGUST", 2), ("SEPTEMBER", 3),
                              ("OCTOBER", 4), ("NOVEMBER", 5), ("DECEMBER", 6)])]),
    ("What's the weather like?", "Hablar del tiempo.",
     lambda r: [b_frase(r, [("IT ", "IS", " sunny today."), ("IT IS ", "RAINING", " now.")],
                        "Completa las frases.")]),
    ("Plurals: -s and -es", "Formar el plural inglés.",
     lambda r: [b_unir(r, [("CAT", "CATS"), ("BOX", "BOXES"),
                           ("DOG", "DOGS"), ("WATCH", "WATCHES")],
                       "Une cada palabra con su plural."),
                b_verdadero_falso(r, [("Después de X, CH o SH se añade -ES.", True),
                                      ("El plural de CAT es CATES.", False)])]),
    ("I have got", "Expresar posesión.",
     lambda r: [b_frase(r, [("I ", "HAVE", " got a bike."), ("She ", "HAS", " got a cat.")],
                        "Completa con HAVE o HAS.")]),
    ("There is / There are", "Expresar existencia.",
     lambda r: [b_frase(r, [("THERE ", "IS", " one book."), ("THERE ", "ARE", " five books.")],
                        "Completa con IS o ARE. Fíjate en si hay uno o varios.")]),
    ("Numbers to 100", "Decenas en inglés.",
     lambda r: [b_unir(r, [("30", "THIRTY"), ("40", "FORTY"), ("50", "FIFTY"),
                           ("60", "SIXTY"), ("100", "ONE HUNDRED")],
                       "Une cada número con su palabra en inglés.")]),
    ("Reading: my day", "Comprensión de un texto breve.",
     lambda r: [b_lectura(r, "My name is Sam. I am seven years old. I go to school every day. "
                             "My favourite subject is Art because I like drawing.",
                          [("What is his name?", "Sam"),
                           ("How old is he?", "Seven"),
                           ("What is his favourite subject?", "Art"),
                           ("Why does he like it?", "Because he likes drawing")])]),
    ("Adjectives", "Describir cosas y personas.",
     lambda r: [b_unir(r, [("BIG", "Grande"), ("SMALL", "Pequeño"), ("HAPPY", "Contento"),
                           ("TIRED", "Cansado"), ("HUNGRY", "Hambriento")],
                       "Une cada adjetivo con su significado.")]),
    ("Describe a person", "Producción descriptiva.",
     lambda r: [b_dibujar(r, "Draw a friend and write three sentences: «He/She is ______. "
                             "He/She has got ______. He/She likes ______.»",
                          "My friend", "mediano")]),
    ("Daily routines", "Acciones habituales.",
     lambda r: [b_ordenar(r, [("I wake up.", 1), ("I have breakfast.", 2),
                              ("I go to school.", 3), ("I do my homework.", 4),
                              ("I go to bed.", 5)])]),
    ("Can and can't", "Expresar habilidad.",
     lambda r: [b_frase(r, [("I ", "CAN", " swim."), ("A fish ", "CAN'T", " fly.")],
                        "Completa con CAN o CAN'T.")]),
    ("Classify: animals", "Clasificación con criterio en inglés.",
     lambda r: [b_clasificar(r, ["CAN FLY", "CAN'T FLY"],
                             [("BIRD", 0), ("DOG", 1), ("BUTTERFLY", 0),
                              ("FISH", 1), ("BEE", 0), ("CAT", 1)])]),
    ("The missing word", "Completar frases con sentido.",
     lambda r: [b_frase(r, [("The sky is ", "BLUE", "."), ("Grass is ", "GREEN", "."),
                            ("Snow is ", "WHITE", ".")])]),
    ("Reading: the park", "Comprensión con vocabulario acumulado.",
     lambda r: [b_lectura(r, "There is a big park near my house. There are three trees and "
                             "two benches. On Saturdays I play football there with my friends.",
                          [("Where is the park?", "Near his house"),
                           ("How many trees are there?", "Three"),
                           ("What does he do on Saturdays?", "Play football")])]),
    ("Write about you", "Producción escrita personal.",
     lambda r: [b_dibujar(r, "Write about yourself in English: your name, your age, "
                             "what you like and what you can do.", "About me", "mediano")]),
    ("Repaso: sentences in English", "Evaluación del curso.",
     lambda r: [b_frase(r, [("I ", "AM", " seven."), ("THERE ", "ARE", " two cats."),
                            ("I ", "CAN", " read.")]),
                b_lectura(r, "Anna has got a red bike. She rides it in the park every afternoon.",
                          [("What has Anna got?", "A red bike"),
                           ("Where does she ride it?", "In the park")])]),
]

CURSO_7 = [
    ("Present simple", "El tiempo verbal más usado.",
     lambda r: [b_frase(r, [("I ", "PLAY", " football."), ("She ", "PLAYS", " the piano."),
                            ("They ", "PLAY", " together.")],
                        "Completa con PLAY o PLAYS. Recuerda la -s de he/she/it.")]),
    ("The third person -s", "Regla de la tercera persona.",
     lambda r: [b_verdadero_falso(r, [
         ("Con HE, SHE e IT el verbo lleva -s.", True),
         ("Se dice «he play football».", False),
         ("Se dice «they live in Madrid».", True)])]),
    ("Negative sentences", "Formar la negación.",
     lambda r: [b_frase(r, [("I ", "DON'T", " like onions."), ("He ", "DOESN'T", " play tennis.")],
                        "Completa con DON'T o DOESN'T.")]),
    ("Questions with DO", "Formular preguntas en presente.",
     lambda r: [b_frase(r, [("", "DO", " you like pizza?"), ("", "DOES", " she speak English?")],
                        "Completa las preguntas con DO o DOES.")]),
    ("Telling the time", "Decir la hora en inglés.",
     lambda r: [b_unir(r, [("3:00", "THREE O'CLOCK"), ("4:15", "QUARTER PAST FOUR"),
                           ("5:30", "HALF PAST FIVE"), ("6:45", "QUARTER TO SEVEN")],
                       "Une cada hora con su forma en inglés.")]),
    ("Reading: a school day", "Comprensión de texto largo.",
     lambda r: [b_lectura(r, "Every morning Leo gets up at half past seven. He has breakfast with "
                             "his sister and they walk to school together. Lessons start at nine "
                             "o'clock. His favourite lesson is Science.",
                          [("What time does Leo get up?", "At half past seven"),
                           ("Who does he have breakfast with?", "His sister"),
                           ("How do they go to school?", "They walk"),
                           ("What is his favourite lesson?", "Science")])]),
    ("Past simple: WAS and WERE", "Iniciación al pasado.",
     lambda r: [b_frase(r, [("I ", "WAS", " at home."), ("They ", "WERE", " very happy.")],
                        "Completa con WAS o WERE.")]),
    ("Regular past verbs", "El pasado regular con -ed.",
     lambda r: [b_unir(r, [("PLAY", "PLAYED"), ("WALK", "WALKED"),
                           ("WATCH", "WATCHED"), ("LIKE", "LIKED")],
                       "Une cada verbo con su pasado.")]),
    ("Irregular past verbs", "Los pasados que hay que memorizar.",
     lambda r: [b_unir(r, [("GO", "WENT"), ("EAT", "ATE"), ("SEE", "SAW"),
                           ("HAVE", "HAD"), ("MAKE", "MADE")],
                       "Une cada verbo irregular con su pasado.")]),
    ("Comparatives", "Comparar dos cosas.",
     lambda r: [b_unir(r, [("BIG", "BIGGER"), ("SMALL", "SMALLER"),
                           ("FAST", "FASTER"), ("GOOD", "BETTER")],
                       "Une cada adjetivo con su comparativo.")]),
    ("Prepositions of time", "IN, ON y AT.",
     lambda r: [b_clasificar(r, ["IN", "ON", "AT"],
                             [("summer", 0), ("Monday", 1), ("3 o'clock", 2),
                              ("January", 0), ("my birthday", 1), ("night", 2)])]),
    ("Countries and nationalities", "Vocabulario del mundo.",
     lambda r: [b_unir(r, [("SPAIN", "SPANISH"), ("FRANCE", "FRENCH"),
                           ("ITALY", "ITALIAN"), ("ENGLAND", "ENGLISH")],
                       "Une cada país con su nacionalidad.")]),
    ("Writing: my weekend", "Producción escrita en pasado.",
     lambda r: [b_dibujar(r, "Write about last weekend in English. Use the past: "
                             "«Last Saturday I went to… I played… I ate…»",
                          "My weekend", "mediano")]),
    ("Reading: the recycling club", "Comprensión de texto informativo.",
     lambda r: [b_lectura(r, "At our school we have a recycling club. Every Friday we collect paper "
                             "and plastic. Last month we collected fifty kilos of paper and we "
                             "planted two trees in the playground.",
                          [("When does the club meet?", "Every Friday"),
                           ("What do they collect?", "Paper and plastic"),
                           ("How much paper did they collect?", "Fifty kilos"),
                           ("What did they plant?", "Two trees")])]),
    ("Question words", "WHAT, WHERE, WHEN, WHO, WHY.",
     lambda r: [b_unir(r, [("WHAT", "Qué"), ("WHERE", "Dónde"), ("WHEN", "Cuándo"),
                           ("WHO", "Quién"), ("WHY", "Por qué")],
                       "Une cada palabra interrogativa con su significado.")]),
    ("Ask the question", "Producir preguntas completas.",
     lambda r: [b_frase(r, [("", "WHERE", " do you live?"), ("", "WHEN", " is your birthday?"),
                            ("", "WHO", " is your best friend?")],
                        "Completa cada pregunta con la palabra interrogativa correcta.")]),
    ("Jobs", "Vocabulario de profesiones.",
     lambda r: [b_unir(r, [("👩‍⚕️", "DOCTOR"), ("👨‍🍳", "COOK"), ("👩‍🏫", "TEACHER"),
                           ("🧑‍🚒", "FIREFIGHTER"), ("👮", "POLICE OFFICER")],
                       "Une cada profesión con su nombre en inglés.")]),
    ("Spelling", "Ortografía de palabras largas.",
     lambda r: [b_completar(r, [("🎂", "BIRTHDAY", 5), ("📚", "LIBRARY", 3),
                                ("🌦️", "WEATHER", 4), ("🥪", "SANDWICH", 4)])]),
    ("A short dialogue", "Interacción oral escrita.",
     lambda r: [b_ordenar(r, [("Hello! What's your name?", 1), ("My name is Sara.", 2),
                              ("Nice to meet you, Sara.", 3), ("Nice to meet you too!", 4)],
                          "Order the dialogue from 1 to 4.")]),
    ("Repaso final", "Evaluación global del curso.",
     lambda r: [b_frase(r, [("She ", "PLAYS", " tennis."), ("I ", "DON'T", " like it."),
                            ("Yesterday I ", "WENT", " home.")]),
                b_lectura(r, "Tom is eight. He lives in London with his family. "
                             "He has got a dog called Max. Every afternoon they go to the park.",
                          [("How old is Tom?", "Eight"),
                           ("Where does he live?", "In London"),
                           ("What is his dog called?", "Max")])]),
]

CURRICULO = {2: CURSO_2, 3: CURSO_3, 4: CURSO_4, 5: CURSO_5, 6: CURSO_6, 7: CURSO_7}
