# -*- coding: utf-8 -*-
"""
Curriculo de Lenguaje: 20 fichas por curso, dificultad creciente.

Progresion: del trazo y el vocabulario oral (2 anos) a la comprension lectora y
la ortografia basica (7 anos), pasando por vocales, consonantes, silabas y
primeras frases en el orden habitual de Infantil y primer ciclo de Primaria.
"""

from generar_fichas import (
    b_colorear, b_concepto, b_contar, b_emparejar, b_trazo, b_unir,
)
from bloques_texto import (
    b_clasificar, b_completar, b_dibujar, b_escritura, b_lectura, b_ordenar,
    b_silabas, b_verdadero_falso,
)


CURSO_2 = [
    ("Trazos de arriba abajo", "Controlar el trazo vertical como base de la escritura.",
     lambda r: [b_trazo(r, ["|", "|", "|"], 6, "Repasa las líneas de arriba abajo sin levantar la cera.")]),
    ("Trazos tumbados", "Controlar el trazo horizontal de izquierda a derecha.",
     lambda r: [b_trazo(r, ["—", "—", "—"], 6, "Repasa las líneas de izquierda a derecha.")]),
    ("El círculo con el dedo", "Trazo circular, previo a las letras redondas.",
     lambda r: [b_trazo(r, ["O", "O", "O"], 5, "Repasa el círculo empezando siempre arriba.")]),
    ("¿Qué animal hace así?", "Asociar sonido y animal (conciencia fonológica oral).",
     lambda r: [b_unir(r, [("🐶 Guau", "🐶"), ("🐱 Miau", "🐱"), ("🐮 Muu", "🐮")],
                       "El adulto lee el sonido y el peque une con el animal.")]),
    ("Igual y diferente", "Discriminación visual, base del reconocimiento de letras.",
     lambda r: [b_emparejar(r, 3)]),
    ("Trazos de olitas", "Trazo ondulado continuo.",
     lambda r: [b_trazo(r, ["∿", "∿", "∿"], 5, "Repasa las olas del mar sin parar.")]),
    ("Mi cara", "Vocabulario del cuerpo y expresión gráfica.",
     lambda r: [b_dibujar(r, "Dibuja tu cara: los ojos, la nariz y la boca.", "Este soy yo")]),
    ("Grande y pequeño", "Vocabulario de conceptos básicos.",
     lambda r: [b_concepto(r, [("🐘", "grande"), ("🐭", "pequeño"), ("🌳", "grande")],
                           "Señala y di en voz alta: ¿es GRANDE o PEQUEÑO?")]),
    ("Trazos en zigzag", "Trazo quebrado, control de cambios de dirección.",
     lambda r: [b_trazo(r, ["∧", "∧", "∧"], 5, "Repasa la montaña: sube y baja.")]),
    ("Los colores que veo", "Vocabulario de colores.",
     lambda r: [b_colorear(r, 3, 4)]),
    ("Encuentra el que se repite", "Atención visual sostenida.",
     lambda r: [b_emparejar(r, 4)]),
    ("La letra A", "Primer contacto con una grafía concreta.",
     lambda r: [b_trazo(r, ["A"], 6, "Repasa la letra A. ¡Es una montaña con cinturón!")]),
    ("Mi familia", "Vocabulario familiar y expresión oral.",
     lambda r: [b_dibujar(r, "Dibuja a las personas que viven contigo.", "Mi familia")]),
    ("La letra E", "Grafía de la segunda vocal.",
     lambda r: [b_trazo(r, ["E"], 6, "Repasa la letra E: un palo y tres brazos.")]),
    ("Dentro y fuera", "Vocabulario espacial.",
     lambda r: [b_concepto(r, [("🐱", "dentro"), ("🐶", "fuera"), ("🐦", "dentro")],
                           "Colorea lo que está DENTRO de la casa.")]),
    ("La letra I", "Grafía de la tercera vocal.",
     lambda r: [b_trazo(r, ["I"], 6, "Repasa la letra I: un palito y su puntito.")]),
    ("Cuenta cuántos hay", "Vocabulario de cantidad ligado al lenguaje.",
     lambda r: [b_contar(r, 3, 3)]),
    ("La letra O", "Grafía de la cuarta vocal.",
     lambda r: [b_trazo(r, ["O"], 6, "Repasa la letra O. ¡Es un círculo perfecto!")]),
    ("La letra U", "Grafía de la quinta vocal.",
     lambda r: [b_trazo(r, ["U"], 6, "Repasa la letra U: es como un vasito.")]),
    ("Repaso: mis primeras letras", "Consolidar las cinco vocales trazadas.",
     lambda r: [b_trazo(r, ["A", "E", "I", "O", "U"], 4), b_emparejar(r, 3)]),
]

CURSO_3 = [
    ("La vocal A", "Reconocer y trazar la A, y su sonido inicial.",
     lambda r: [b_trazo(r, ["A", "a"], 5),
                b_unir(r, [("A", "🌳 Árbol"), ("A", "🕷️ Araña"), ("A", "🌊 Agua")],
                       "Une la A con los dibujos que empiezan por A.")]),
    ("La vocal E", "Reconocer y trazar la E.",
     lambda r: [b_trazo(r, ["E", "e"], 5),
                b_unir(r, [("E", "🐘 Elefante"), ("E", "⭐ Estrella"), ("E", "🪜 Escalera")],
                       "Une la E con los dibujos que empiezan por E.")]),
    ("La vocal I", "Reconocer y trazar la I.",
     lambda r: [b_trazo(r, ["I", "i"], 5),
                b_unir(r, [("I", "🏝️ Isla"), ("I", "⛪ Iglesia"), ("I", "🧲 Imán")],
                       "Une la I con los dibujos que empiezan por I.")]),
    ("La vocal O", "Reconocer y trazar la O.",
     lambda r: [b_trazo(r, ["O", "o"], 5),
                b_unir(r, [("O", "🐻 Oso"), ("O", "👂 Oreja"), ("O", "🍂 Otoño")],
                       "Une la O con los dibujos que empiezan por O.")]),
    ("La vocal U", "Reconocer y trazar la U.",
     lambda r: [b_trazo(r, ["U", "u"], 5),
                b_unir(r, [("U", "🍇 Uvas"), ("U", "🦄 Unicornio"), ("U", "💅 Uña")],
                       "Une la U con los dibujos que empiezan por U.")]),
    ("Las cinco vocales", "Recorrer la serie vocálica completa.",
     lambda r: [b_trazo(r, ["A", "E", "I", "O", "U"], 4),
                b_unir(r, [("A", "🐘 Elefante"), ("E", "🌳 Árbol"), ("I", "🐻 Oso"),
                           ("O", "🍇 Uvas"), ("U", "🏝️ Isla")],
                       "Une cada vocal con el dibujo que empieza por ella.")]),
    ("Mayúscula y minúscula", "Emparejar las dos formas de cada vocal.",
     lambda r: [b_unir(r, [("A", "a"), ("E", "e"), ("I", "i"), ("O", "o"), ("U", "u")],
                       "Une cada letra grande con su letra pequeña.")]),
    ("¿Empieza por A?", "Discriminar el sonido inicial.",
     lambda r: [b_clasificar(r, ["Empieza por A", "No empieza por A"],
                             [("🕷️ Araña", 0), ("🌳 Árbol", 0), ("🐶 Perro", 1),
                              ("🌊 Agua", 0), ("🐱 Gato", 1), ("🌙 Luna", 1)])]),
    ("El trazo de la M", "Primera consonante: grafía de la M.",
     lambda r: [b_trazo(r, ["M", "m"], 5, "Repasa la M: sube, baja, sube y baja.")]),
    ("MA, ME, MI, MO, MU", "Primeras sílabas con la M.",
     lambda r: [b_trazo(r, ["MA", "ME", "MI", "MO", "MU"], 3, "Repasa y lee cada sílaba en voz alta.")]),
    ("El trazo de la P", "Grafía de la P.",
     lambda r: [b_trazo(r, ["P", "p"], 5, "Repasa la P: un palo y una barriga.")]),
    ("PA, PE, PI, PO, PU", "Primeras sílabas con la P.",
     lambda r: [b_trazo(r, ["PA", "PE", "PI", "PO", "PU"], 3, "Repasa y lee cada sílaba en voz alta.")]),
    ("Mi primera palabra: MAMÁ", "Leer y escribir una palabra completa.",
     lambda r: [b_escritura(r, [("👩", "MAMÁ"), ("👨", "PAPÁ")])]),
    ("El trazo de la L", "Grafía de la L.",
     lambda r: [b_trazo(r, ["L", "l"], 5, "Repasa la L: baja y gira a la derecha.")]),
    ("LA, LE, LI, LO, LU", "Sílabas con la L.",
     lambda r: [b_trazo(r, ["LA", "LE", "LI", "LO", "LU"], 3, "Repasa y lee cada sílaba en voz alta.")]),
    ("Palabras con L", "Leer palabras de dos sílabas.",
     lambda r: [b_escritura(r, [("🌙", "LUNA"), ("🥛", "LECHE")])]),
    ("Palmadas: las sílabas", "Segmentar palabras en sílabas.",
     lambda r: [b_silabas(r, [("☀️", "SOL"), ("🐱", "GATO"), ("🏠", "CASA")])]),
    ("Clasifica los dibujos", "Categorizar vocabulario.",
     lambda r: [b_clasificar(r, ["Animales", "Comida"],
                             [("🐶", 0), ("🍎", 1), ("🐱", 0), ("🍌", 1), ("🐰", 0), ("🍇", 1)])]),
    ("Dibuja lo que te gusta", "Expresión gráfica y vocabulario oral.",
     lambda r: [b_dibujar(r, "Dibuja tu juguete favorito y di su nombre en voz alta.", "Mi juguete")]),
    ("Repaso: vocales y sílabas", "Evaluación del curso.",
     lambda r: [b_trazo(r, ["A", "E", "I", "O", "U"], 3),
                b_escritura(r, [("👩", "MAMÁ"), ("🌙", "LUNA")])]),
]

CURSO_4 = [
    ("Repaso de las vocales", "Recuperar la serie vocálica.",
     lambda r: [b_trazo(r, ["A", "E", "I", "O", "U"], 4),
                b_clasificar(r, ["Vocal", "Consonante"],
                             [("A", 0), ("M", 1), ("E", 0), ("P", 1), ("O", 0), ("L", 1)])]),
    ("La S y sus sílabas", "Grafía y sílabas de la S.",
     lambda r: [b_trazo(r, ["S", "s"], 5), b_trazo(r, ["SA", "SE", "SI", "SO", "SU"], 3)]),
    ("Palabras con S", "Leer y escribir palabras con S.",
     lambda r: [b_escritura(r, [("☀️", "SOL"), ("🪑", "SILLA"), ("🐍", "SERPIENTE")])]),
    ("La T y sus sílabas", "Grafía y sílabas de la T.",
     lambda r: [b_trazo(r, ["T", "t"], 5), b_trazo(r, ["TA", "TE", "TI", "TO", "TU"], 3)]),
    ("Palabras con T", "Leer y escribir palabras con T.",
     lambda r: [b_escritura(r, [("🍅", "TOMATE"), ("🐢", "TORTUGA")])]),
    ("La N y sus sílabas", "Grafía y sílabas de la N.",
     lambda r: [b_trazo(r, ["N", "n"], 5), b_trazo(r, ["NA", "NE", "NI", "NO", "NU"], 3)]),
    ("La letra que falta", "Completar palabras conocidas.",
     lambda r: [b_completar(r, [("☀️", "SOL", 1), ("🐱", "GATO", 0),
                                ("🌙", "LUNA", 2), ("🏠", "CASA", 3)])]),
    ("La D y sus sílabas", "Grafía y sílabas de la D.",
     lambda r: [b_trazo(r, ["D", "d"], 5), b_trazo(r, ["DA", "DE", "DI", "DO", "DU"], 3)]),
    ("Cuenta las sílabas", "Segmentar palabras de dos y tres sílabas.",
     lambda r: [b_silabas(r, [("🐱", "GATO"), ("🌸", "FLOR"), ("🦋", "MARIPOSA"), ("🍫", "CHOCOLATE")])]),
    ("La C y sus sílabas", "Grafía de la C ante A, O y U.",
     lambda r: [b_trazo(r, ["C", "c"], 5), b_trazo(r, ["CA", "CO", "CU"], 4)]),
    ("Palabras con C", "Leer y escribir palabras con C.",
     lambda r: [b_escritura(r, [("🏠", "CASA"), ("🚗", "COCHE"), ("🥄", "CUCHARA")])]),
    ("Clasifica por sílabas", "Ordenar palabras por su longitud.",
     lambda r: [b_clasificar(r, ["1 sílaba", "2 sílabas", "3 sílabas"],
                             [("SOL", 0), ("GATO", 1), ("PELOTA", 2),
                              ("PAN", 0), ("CASA", 1), ("CAMISETA", 2)])]),
    ("La R fuerte", "Grafía de la R y su sonido fuerte.",
     lambda r: [b_trazo(r, ["R", "r"], 5), b_escritura(r, [("🐭", "RATÓN"), ("🌹", "ROSA")])]),
    ("Mayúscula al empezar", "Norma ortográfica básica.",
     lambda r: [b_escritura(r, [("🐶", "PERRO"), ("🌳", "ÁRBOL")],
                            "Escribe cada palabra empezando siempre por mayúscula.")]),
    ("Ordena la frase", "Construir una frase de tres palabras.",
     lambda r: [b_ordenar(r, [("EL", 1), ("GATO", 2), ("DUERME", 3)])]),
    ("Mi nombre", "Escribir el nombre propio.",
     lambda r: [b_dibujar(r, "Escribe tu nombre en grande y decóralo con tus colores.",
                          "Mi nombre", "mediano")]),
    ("¿Qué palabra es?", "Asociar dibujo y palabra escrita.",
     lambda r: [b_unir(r, [("☀️", "SOL"), ("🌙", "LUNA"), ("🏠", "CASA"), ("🐱", "GATO")],
                       "Une cada dibujo con su palabra.")]),
    ("La F y la B", "Dos consonantes que se confunden.",
     lambda r: [b_trazo(r, ["F", "B"], 4),
                b_escritura(r, [("🌸", "FLOR"), ("⚽", "BALÓN")])]),
    ("Frases de dos palabras", "Primeras frases con sentido.",
     lambda r: [b_escritura(r, [("🐱", "EL GATO"), ("☀️", "EL SOL")],
                            "Repasa y copia cada grupo de palabras.")]),
    ("Repaso: leo y escribo", "Evaluación del curso.",
     lambda r: [b_silabas(r, [("🏠", "CASA"), ("🌙", "LUNA")]),
                b_escritura(r, [("☀️", "SOL"), ("🐱", "GATO")])]),
]

CURSO_5 = [
    ("El abecedario completo", "Recorrer las 27 letras.",
     lambda r: [b_trazo(r, ["A", "B", "C", "D", "E", "F"], 3),
                b_trazo(r, ["G", "H", "I", "J", "K", "L"], 3)]),
    ("De la M a la Z", "Segunda mitad del abecedario.",
     lambda r: [b_trazo(r, ["M", "N", "Ñ", "O", "P", "Q"], 3),
                b_trazo(r, ["R", "S", "T", "U", "V", "W", "X", "Y", "Z"], 2)]),
    ("Orden alfabético", "Situar letras en la serie.",
     lambda r: [b_ordenar(r, [("A", 1), ("B", 2), ("C", 3), ("D", 4), ("E", 5)])]),
    ("Sílabas trabadas: BR y BL", "Grupos consonánticos.",
     lambda r: [b_trazo(r, ["BRA", "BRE", "BLA", "BLE"], 3),
                b_escritura(r, [("🌉", "BRAZO"), ("⬜", "BLANCO")])]),
    ("Sílabas trabadas: PR y PL", "Grupos consonánticos.",
     lambda r: [b_trazo(r, ["PRA", "PRE", "PLA", "PLE"], 3),
                b_escritura(r, [("🍽️", "PLATO"), ("🎁", "PREMIO")])]),
    ("Sílabas trabadas: TR y DR", "Grupos consonánticos.",
     lambda r: [b_escritura(r, [("🚂", "TREN"), ("🐉", "DRAGÓN"), ("🌳", "TRONCO")])]),
    ("Cuenta y separa sílabas", "Segmentación de palabras largas.",
     lambda r: [b_silabas(r, [("🦋", "MARIPOSA"), ("🐘", "ELEFANTE"),
                              ("🏫", "ESCUELA"), ("🍫", "CHOCOLATE")])]),
    ("La letra que falta", "Completar palabras de tres sílabas.",
     lambda r: [b_completar(r, [("🦋", "MARIPOSA", 3), ("🐘", "ELEFANTE", 0),
                                ("🍅", "TOMATE", 2), ("🚗", "COCHE", 1)])]),
    ("Ordena la frase", "Sintaxis de frases de cuatro palabras.",
     lambda r: [b_ordenar(r, [("MI", 1), ("PERRO", 2), ("COME", 3), ("PAN", 4)])]),
    ("Mayúsculas y punto", "Normas de la frase escrita.",
     lambda r: [b_verdadero_falso(r, [
         ("Las frases empiezan por mayúscula.", True),
         ("Las frases terminan con un punto.", True),
         ("Los nombres de personas van en minúscula.", False),
         ("Después del punto se escribe minúscula.", False)])]),
    ("Palabras que riman", "Conciencia fonológica de la rima.",
     lambda r: [b_unir(r, [("GATO", "PATO"), ("RATÓN", "BOTÓN"),
                           ("FLOR", "COLOR"), ("PAN", "IMÁN")],
                       "Une las palabras que suenan parecido al final.")]),
    ("Leo mi primera frase", "Comprensión de una frase aislada.",
     lambda r: [b_lectura(r, "El gato de Ana es blanco y duerme en el sofá.",
                          [("¿De quién es el gato?", "De Ana"),
                           ("¿De qué color es?", "Blanco"),
                           ("¿Dónde duerme?", "En el sofá")])]),
    ("Singular y plural", "Formar el plural con -s y -es.",
     lambda r: [b_unir(r, [("GATO", "GATOS"), ("FLOR", "FLORES"),
                           ("CASA", "CASAS"), ("PAN", "PANES")],
                       "Une cada palabra con su plural.")]),
    ("Clasifica las palabras", "Categorías semánticas.",
     lambda r: [b_clasificar(r, ["Personas", "Animales", "Cosas"],
                             [("MAMÁ", 0), ("PERRO", 1), ("SILLA", 2),
                              ("NIÑO", 0), ("GATO", 1), ("MESA", 2)])]),
    ("La Ñ", "Una letra propia del español.",
     lambda r: [b_trazo(r, ["Ñ", "ñ"], 5),
                b_escritura(r, [("🧒", "NIÑO"), ("🏔️", "MONTAÑA")])]),
    ("Escribo una frase", "Producción escrita guiada.",
     lambda r: [b_escritura(r, [("🐶", "MI PERRO CORRE"), ("☀️", "HACE SOL")],
                            "Repasa la frase y después escríbela tú solo.")]),
    ("Cuento corto", "Comprensión de un texto breve.",
     lambda r: [b_lectura(r, "Lucía va al parque con su pelota roja. Allí juega con Marta.",
                          [("¿Cómo se llama la niña?", "Lucía"),
                           ("¿De qué color es la pelota?", "Roja"),
                           ("¿Con quién juega?", "Con Marta")])]),
    ("Preguntas y respuestas", "Signos de interrogación.",
     lambda r: [b_verdadero_falso(r, [
         ("Las preguntas llevan ¿ al principio y ? al final.", True),
         ("Solo se escribe el signo del final.", False),
         ("«¿Cómo te llamas?» es una pregunta.", True)])]),
    ("Dibuja y escribe", "Relacionar dibujo y texto propio.",
     lambda r: [b_dibujar(r, "Dibuja tu animal favorito y escribe su nombre debajo.",
                          "Mi animal favorito", "mediano")]),
    ("Repaso: leo y comprendo", "Evaluación del curso.",
     lambda r: [b_silabas(r, [("🦋", "MARIPOSA"), ("🏫", "ESCUELA")]),
                b_lectura(r, "El sol sale por la mañana y la luna sale por la noche.",
                          [("¿Cuándo sale el sol?", "Por la mañana"),
                           ("¿Y la luna?", "Por la noche")])]),
]

CURSO_6 = [
    ("Repaso del abecedario", "Consolidar el orden alfabético.",
     lambda r: [b_ordenar(r, [("CASA", 1), ("DEDO", 2), ("FLOR", 3), ("GATO", 4), ("LUNA", 5)],
                          "Ordena estas palabras por orden alfabético, del 1 al 5.")]),
    ("La sílaba tónica", "Identificar dónde recae el acento.",
     lambda r: [b_silabas(r, [("🐱", "GATO"), ("🦋", "MARIPOSA"), ("🍋", "LIMÓN"), ("🏠", "CASA")],
                          "Separa en sílabas y rodea la sílaba que suena más fuerte.")]),
    ("Palabras con MP y MB", "Regla ortográfica de la M antes de P y B.",
     lambda r: [b_escritura(r, [("💡", "BOMBILLA"), ("🥁", "TAMBOR"), ("👑", "CAMPANA")]),
                b_verdadero_falso(r, [("Antes de P y B se escribe M, nunca N.", True),
                                      ("Se escribe «canpana».", False)])]),
    ("El nombre y el artículo", "Concordancia de género y número.",
     lambda r: [b_unir(r, [("EL", "PERRO"), ("LA", "CASA"), ("LOS", "NIÑOS"), ("LAS", "FLORES")],
                       "Une cada artículo con el nombre que le corresponde.")]),
    ("Comprensión: la excursión", "Extraer información de un texto.",
     lambda r: [b_lectura(r,
                          "El martes fuimos de excursión a la granja. Vimos seis vacas, "
                          "tres cerdos y un caballo marrón. Comimos el bocadillo debajo de un árbol.",
                          [("¿Qué día fue la excursión?", "El martes"),
                           ("¿Cuántas vacas vieron?", "Seis"),
                           ("¿De qué color era el caballo?", "Marrón"),
                           ("¿Dónde comieron?", "Debajo de un árbol")])]),
    ("Palabras con B y V", "Distinguir dos grafías del mismo sonido.",
     lambda r: [b_clasificar(r, ["Se escribe con B", "Se escribe con V"],
                             [("BARCO", 0), ("VACA", 1), ("BOCA", 0),
                              ("VENTANA", 1), ("BOTA", 0), ("VERDE", 1)])]),
    ("El verbo: qué hacemos", "Reconocer acciones.",
     lambda r: [b_clasificar(r, ["Es una acción", "No es una acción"],
                             [("CORRER", 0), ("MESA", 1), ("SALTAR", 0),
                              ("COMER", 0), ("SILLA", 1), ("ÁRBOL", 1)])]),
    ("Escribo una frase larga", "Producción de frases con complemento.",
     lambda r: [b_escritura(r, [("🐕", "MI PERRO CORRE EN EL PARQUE"),
                                ("📖", "LEO UN CUENTO POR LA NOCHE")],
                            "Repasa cada frase y cópiala en la línea de abajo.")]),
    ("Ordena el cuento", "Secuenciar una narración.",
     lambda r: [b_ordenar(r, [("Ana se despierta.", 1), ("Se viste y desayuna.", 2),
                              ("Va al colegio.", 3), ("Vuelve a casa y cena.", 4)])]),
    ("Palabras con G y J", "Regla ortográfica de GE/GI y JE/JI.",
     lambda r: [b_clasificar(r, ["Con G", "Con J"],
                             [("GIRASOL", 0), ("JIRAFA", 1), ("GENTE", 0),
                              ("JUGAR", 1), ("GIGANTE", 0), ("JAMÓN", 1)])]),
    ("Sinónimos", "Palabras que significan lo mismo.",
     lambda r: [b_unir(r, [("BONITO", "GUAPO"), ("CONTENTO", "ALEGRE"),
                           ("GRANDE", "ENORME"), ("RÁPIDO", "VELOZ")],
                       "Une las palabras que significan lo mismo.")]),
    ("Antónimos", "Palabras que significan lo contrario.",
     lambda r: [b_unir(r, [("ALTO", "BAJO"), ("FRÍO", "CALIENTE"),
                           ("DÍA", "NOCHE"), ("ABRIR", "CERRAR")],
                       "Une cada palabra con su contraria.")]),
    ("La coma en las listas", "Uso básico de la coma.",
     lambda r: [b_escritura(r, [("🍎", "COMPRÉ PAN, LECHE Y FRUTA")],
                            "Copia la frase respetando las comas."),
                b_verdadero_falso(r, [("La coma separa los elementos de una lista.", True),
                                      ("Antes de «y» final se pone coma.", False)])]),
    ("Comprensión: el mercado", "Localizar datos concretos.",
     lambda r: [b_lectura(r,
                          "Mamá fue al mercado el sábado. Compró cuatro manzanas, "
                          "dos barras de pan y un kilo de tomates. Pagó con un billete de veinte euros.",
                          [("¿Qué día fue al mercado?", "El sábado"),
                           ("¿Cuántas manzanas compró?", "Cuatro"),
                           ("¿Con cuánto pagó?", "Con veinte euros")])]),
    ("Palabras con H muda", "Ortografía de la H.",
     lambda r: [b_escritura(r, [("🏠", "HOGAR"), ("🥚", "HUEVO"), ("🌿", "HIERBA")]),
                b_verdadero_falso(r, [("La H no suena, pero se escribe.", True),
                                      ("«Uevo» se escribe sin H.", False),
                                      ("«Hola» empieza por H.", True)])]),
    ("Masculino y femenino", "Formar el femenino.",
     lambda r: [b_unir(r, [("NIÑO", "NIÑA"), ("GATO", "GATA"),
                           ("PROFESOR", "PROFESORA"), ("LEÓN", "LEONA")],
                       "Une cada palabra con su femenino.")]),
    ("Escribo un recado", "Escritura funcional.",
     lambda r: [b_dibujar(r, "Escribe una nota a alguien de tu familia contándole qué has hecho hoy.",
                          "Mi recado", "mediano")]),
    ("Signos de exclamación", "Entonación en la escritura.",
     lambda r: [b_verdadero_falso(r, [
         ("«¡Qué bonito!» lleva signos de exclamación.", True),
         ("Los signos de exclamación solo van al final.", False),
         ("Sirven para mostrar sorpresa o alegría.", True)])]),
    ("Amplío la frase", "Enriquecer una oración con adjetivos.",
     lambda r: [b_escritura(r, [("🌸", "LA FLOR ROJA ES MUY BONITA"),
                                ("🐦", "EL PÁJARO PEQUEÑO CANTA")],
                            "Copia cada frase y subraya la palabra que dice cómo es.")]),
    ("Repaso: escribo y comprendo", "Evaluación del curso.",
     lambda r: [b_lectura(r, "Pablo tiene siete años y le gusta pintar. Su color favorito es el azul.",
                          [("¿Cuántos años tiene Pablo?", "Siete"),
                           ("¿Qué le gusta hacer?", "Pintar"),
                           ("¿Cuál es su color favorito?", "El azul")]),
                b_silabas(r, [("🖍️", "PINTURA"), ("💙", "AZUL")])]),
]

CURSO_7 = [
    ("El punto y la mayúscula", "Repasar la estructura de la oración.",
     lambda r: [b_escritura(r, [("📚", "HOY HE LEÍDO UN CUENTO NUEVO.")],
                            "Copia la frase con su mayúscula inicial y su punto final."),
                b_verdadero_falso(r, [("Cada oración empieza por mayúscula.", True),
                                      ("El punto y aparte cambia de párrafo.", True),
                                      ("Los nombres propios van en minúscula.", False)])]),
    ("Sustantivo, adjetivo y verbo", "Clases de palabras.",
     lambda r: [b_clasificar(r, ["Sustantivo", "Adjetivo", "Verbo"],
                             [("PERRO", 0), ("BONITO", 1), ("CORRER", 2),
                              ("CASA", 0), ("ALTO", 1), ("SALTAR", 2)])]),
    ("Agudas, llanas y esdrújulas", "Clasificar por sílaba tónica.",
     lambda r: [b_silabas(r, [("🍋", "LIMÓN"), ("🌳", "ÁRBOL"), ("📱", "TELÉFONO")],
                          "Separa en sílabas y rodea la tónica."),
                b_clasificar(r, ["Aguda", "Llana", "Esdrújula"],
                             [("SOFÁ", 0), ("LÁPIZ", 1), ("MÚSICA", 2),
                              ("RATÓN", 0), ("MESA", 1), ("PÁJARO", 2)])]),
    ("Comprensión: la biblioteca", "Comprensión literal e inferencial.",
     lambda r: [b_lectura(r,
                          "Los martes por la tarde, Marta va a la biblioteca del barrio. "
                          "Puede llevarse tres libros a casa durante quince días. Si los devuelve "
                          "tarde, no puede sacar más libros durante una semana.",
                          [("¿Qué día va Marta a la biblioteca?", "Los martes"),
                           ("¿Cuántos libros puede llevarse?", "Tres"),
                           ("¿Cuánto tiempo puede tenerlos?", "Quince días"),
                           ("¿Qué pasa si los devuelve tarde?", "No puede sacar libros una semana")])]),
    ("Palabras con LL y Y", "Ortografía de dos grafías próximas.",
     lambda r: [b_clasificar(r, ["Con LL", "Con Y"],
                             [("LLAVE", 0), ("YOGUR", 1), ("CABALLO", 0),
                              ("PLAYA", 1), ("GALLINA", 0), ("AYER", 1)])]),
    ("Presente, pasado y futuro", "Los tiempos verbales.",
     lambda r: [b_unir(r, [("Ayer", "COMÍ"), ("Hoy", "COMO"), ("Mañana", "COMERÉ")],
                       "Une cada momento con su forma verbal."),
                b_clasificar(r, ["Pasado", "Presente", "Futuro"],
                             [("JUGUÉ", 0), ("JUEGO", 1), ("JUGARÉ", 2),
                              ("CANTÉ", 0), ("CANTO", 1), ("CANTARÉ", 2)])]),
    ("La tilde en las agudas", "Regla de acentuación.",
     lambda r: [b_verdadero_falso(r, [
         ("Las agudas llevan tilde si acaban en vocal, N o S.", True),
         ("«Camión» lleva tilde porque acaba en N.", True),
         ("«Reloj» lleva tilde.", False),
         ("«Sofá» lleva tilde porque acaba en vocal.", True)])]),
    ("Escribo una descripción", "Producción escrita descriptiva.",
     lambda r: [b_dibujar(r, "Describe tu habitación en cuatro o cinco líneas: cómo es, "
                             "qué hay y qué es lo que más te gusta.", "Mi habitación", "mediano")]),
    ("Sinónimos y antónimos", "Ampliar el vocabulario.",
     lambda r: [b_unir(r, [("VALIENTE", "COBARDE"), ("LIMPIO", "SUCIO"),
                           ("ANTIGUO", "MODERNO"), ("FÁCIL", "DIFÍCIL")],
                       "Une cada palabra con su antónimo."),
                b_unir(r, [("CASA", "VIVIENDA"), ("COCHE", "AUTOMÓVIL"),
                           ("PROFESOR", "MAESTRO")],
                       "Une cada palabra con su sinónimo.")]),
    ("Comprensión: los pingüinos", "Texto informativo.",
     lambda r: [b_lectura(r,
                          "Los pingüinos son aves que no vuelan, pero nadan muy bien. "
                          "Viven en lugares muy fríos y se agrupan para darse calor. "
                          "El pingüino emperador es el más grande de todos.",
                          [("¿Los pingüinos vuelan?", "No, pero nadan bien"),
                           ("¿Por qué se agrupan?", "Para darse calor"),
                           ("¿Cuál es el más grande?", "El pingüino emperador")])]),
    ("El diálogo y la raya", "Escritura de conversaciones.",
     lambda r: [b_escritura(r, [("💬", "—¿VIENES AL PARQUE? —PREGUNTÓ ANA.")],
                            "Copia el diálogo respetando la raya."),
                b_verdadero_falso(r, [("La raya indica que alguien habla.", True),
                                      ("En un diálogo cada personaje empieza en línea nueva.", True),
                                      ("En un diálogo se usan comillas en vez de raya.", False)])]),
    ("Familias de palabras", "Derivación léxica.",
     lambda r: [b_clasificar(r, ["Familia de PAN", "Familia de FLOR"],
                             [("PANADERO", 0), ("FLORISTERÍA", 1), ("PANADERÍA", 0),
                              ("FLORERO", 1), ("PANECILLO", 0), ("FLORECER", 1)])]),
    ("Ordena el texto", "Estructura de una narración.",
     lambda r: [b_ordenar(r, [("Un día, el ratón encontró un queso enorme.", 1),
                              ("Intentó llevárselo, pero pesaba mucho.", 2),
                              ("Llamó a sus amigos para que le ayudaran.", 3),
                              ("Entre todos lo llevaron a la madriguera.", 4),
                              ("Y comieron queso durante una semana.", 5)])]),
    ("Palabras con C, Q y K", "Ortografía del sonido /k/.",
     lambda r: [b_clasificar(r, ["Con C", "Con QU", "Con K"],
                             [("CASA", 0), ("QUESO", 1), ("KOALA", 2),
                              ("COCHE", 0), ("QUIOSCO", 1), ("KILO", 2)])]),
    ("La tilde en las llanas", "Regla de acentuación.",
     lambda r: [b_verdadero_falso(r, [
         ("Las llanas llevan tilde si NO acaban en vocal, N o S.", True),
         ("«Árbol» lleva tilde porque acaba en L.", True),
         ("«Mesa» lleva tilde.", False)])]),
    ("Escribo un cuento corto", "Producción narrativa completa.",
     lambda r: [b_dibujar(r, "Escribe un cuento corto con principio, medio y final. "
                             "Puede empezar así: «Había una vez un dragón que no sabía volar…»",
                          "Mi cuento", "grande")]),
    ("Comprensión: el reciclaje", "Texto expositivo y opinión.",
     lambda r: [b_lectura(r,
                          "Reciclar significa aprovechar los materiales usados para fabricar cosas nuevas. "
                          "El papel va al contenedor azul, los envases al amarillo y el vidrio al verde. "
                          "Reciclando ahorramos energía y ensuciamos menos el planeta.",
                          [("¿Qué significa reciclar?", "Aprovechar materiales usados"),
                           ("¿De qué color es el contenedor del papel?", "Azul"),
                           ("¿Dónde van los envases?", "Al contenedor amarillo"),
                           ("¿Por qué es bueno reciclar?", "Ahorra energía y ensucia menos")])]),
    ("Aumentativos y diminutivos", "Sufijos que cambian el tamaño.",
     lambda r: [b_unir(r, [("CASA", "CASITA"), ("PERRO", "PERRAZO"),
                           ("LIBRO", "LIBRITO"), ("COCHE", "COCHAZO")],
                       "Une cada palabra con su diminutivo o aumentativo.")]),
    ("Repaso de ortografía", "Consolidar las reglas del curso.",
     lambda r: [b_completar(r, [("🐴", "CABALLO", 3), ("🥁", "TAMBOR", 2),
                                ("🏠", "HOGAR", 0), ("🦒", "JIRAFA", 0)]),
                b_clasificar(r, ["Con B", "Con V"],
                             [("BARCO", 0), ("VACA", 1), ("BOTELLA", 0), ("VERANO", 1)])]),
    ("Repaso final", "Evaluación global del curso.",
     lambda r: [b_lectura(r,
                          "En verano, mi familia y yo vamos al pueblo de mis abuelos. "
                          "Allí hay un río donde nos bañamos y un huerto con tomates y lechugas.",
                          [("¿Cuándo van al pueblo?", "En verano"),
                           ("¿De quién es el pueblo?", "De sus abuelos"),
                           ("¿Qué hay en el huerto?", "Tomates y lechugas")]),
                b_silabas(r, [("🍅", "TOMATE"), ("🏞️", "RÍO")])]),
]

CURRICULO = {2: CURSO_2, 3: CURSO_3, 4: CURSO_4, 5: CURSO_5, 6: CURSO_6, 7: CURSO_7}
