# -*- coding: utf-8 -*-
"""
Curriculo de Matematicas: 20 fichas por curso, dificultad creciente.

Cada entrada es (titulo, objetivo, funcion -> lista de bloques). La progresion
va de lo manipulativo y perceptivo (2 anos) al calculo con reagrupacion y las
tablas de multiplicar (7 anos), siguiendo el orden habitual de Infantil y del
primer ciclo de Primaria.
"""

from generar_fichas import (
    b_colorear, b_comparar, b_concepto, b_contar, b_descomponer, b_dobles,
    b_emparejar, b_formas, b_monedas, b_operaciones, b_problema, b_reloj,
    b_rodear, b_serie, b_tabla, b_tantos_como, b_trazo, b_unir, b_vecinos,
)


CURSO_2 = [
    ("Grande y pequeño", "Discriminar tamaños por comparación directa.",
     lambda r: [b_concepto(r, [("🐘", "grande"), ("🐭", "pequeño"), ("🌳", "grande"), ("🌱", "pequeño")],
                           "Rodea de rojo lo GRANDE y de azul lo PEQUEÑO.")]),
    ("Muchos y pocos", "Estimar la cantidad global sin llegar a contar.",
     lambda r: [b_concepto(r, [("⭐", "muchos"), ("🎈", "pocos"), ("🍎", "muchos")],
                           "Marca con una X el grupo donde hay MUCHOS.")]),
    ("El círculo", "Reconocer y trazar la forma circular.",
     lambda r: [b_formas(r, ["circulo"], "Repasa el círculo con el dedo y después con la cera."),
                b_colorear(r, 2, 4)]),
    ("Colorea uno", "Asociar la palabra «uno» con la cantidad 1.",
     lambda r: [b_colorear(r, 3, 4)]),
    ("Igual que este", "Emparejar por identidad visual.",
     lambda r: [b_emparejar(r, 3)]),
    ("Contamos: uno", "Contar el primer número con ayuda del adulto.",
     lambda r: [b_contar(r, 3, 1), b_trazo(r, ["1"], 5)]),
    ("Contamos: dos", "Contar hasta dos.",
     lambda r: [b_contar(r, 3, 2), b_trazo(r, ["2"], 5)]),
    ("Líneas de pie", "Controlar el trazo vertical.",
     lambda r: [b_trazo(r, ["|", "|", "|"], 6, "Repasa las líneas de arriba abajo.")]),
    ("Líneas tumbadas", "Controlar el trazo horizontal.",
     lambda r: [b_trazo(r, ["—", "—", "—"], 6, "Repasa las líneas de izquierda a derecha.")]),
    ("El cuadrado", "Reconocer y trazar el cuadrado.",
     lambda r: [b_formas(r, ["cuadrado"], "Repasa el cuadrado y cuenta sus lados."),
                b_colorear(r, 2, 4)]),
    ("Dentro y fuera", "Nociones espaciales básicas.",
     lambda r: [b_concepto(r, [("🐱", "dentro"), ("🐶", "fuera"), ("🐦", "dentro")],
                           "Colorea lo que está DENTRO de la casa.")]),
    ("Contamos: tres", "Contar hasta tres.",
     lambda r: [b_contar(r, 3, 3), b_trazo(r, ["3"], 5)]),
    ("Alto y bajo", "Comparar alturas.",
     lambda r: [b_concepto(r, [("🦒", "alto"), ("🐢", "bajo"), ("🌳", "alto")],
                           "Rodea lo que es ALTO.")]),
    ("Colorea dos", "Asociar la palabra «dos» con la cantidad 2.",
     lambda r: [b_colorear(r, 3, 5)]),
    ("Encuentra el igual", "Atención visual y emparejamiento.",
     lambda r: [b_emparejar(r, 4)]),
    ("Largo y corto", "Comparar longitudes.",
     lambda r: [b_concepto(r, [("🐍", "largo"), ("🐛", "corto"), ("🚂", "largo")],
                           "Rodea lo que es LARGO.")]),
    ("El triángulo", "Reconocer y trazar el triángulo.",
     lambda r: [b_formas(r, ["triangulo"], "Repasa el triángulo. ¡Tiene tres puntas!"),
                b_colorear(r, 2, 4)]),
    ("Uno, dos y tres", "Recorrer la secuencia numérica del 1 al 3.",
     lambda r: [b_contar(r, 3, 3), b_trazo(r, ["1", "2", "3"], 4)]),
    ("Lleno y vacío", "Noción de capacidad.",
     lambda r: [b_concepto(r, [("🪣", "lleno"), ("🥛", "vacío"), ("🧺", "lleno")],
                           "Colorea lo que está LLENO.")]),
    ("Repaso: formas y cantidades", "Consolidar los aprendizajes del curso.",
     lambda r: [b_formas(r, ["circulo", "cuadrado", "triangulo"]), b_contar(r, 3, 3)]),
]

CURSO_3 = [
    ("El número 1", "Grafía y cantidad del 1.",
     lambda r: [b_trazo(r, ["1"], 6), b_contar(r, 3, 1)]),
    ("El número 2", "Grafía y cantidad del 2.",
     lambda r: [b_trazo(r, ["2"], 6), b_contar(r, 3, 2)]),
    ("Contar hasta 3", "Conteo con correspondencia uno a uno.",
     lambda r: [b_contar(r, 4, 3), b_colorear(r, 2, 4)]),
    ("El número 3", "Grafía y cantidad del 3.",
     lambda r: [b_trazo(r, ["3"], 6), b_contar(r, 3, 3)]),
    ("Círculo y cuadrado", "Discriminar dos formas básicas.",
     lambda r: [b_formas(r, ["circulo", "cuadrado"]), b_emparejar(r, 3)]),
    ("Más y menos", "Comparar dos colecciones.",
     lambda r: [b_comparar(r, 4, 3, True)]),
    ("Contar hasta 4", "Ampliar el rango de conteo.",
     lambda r: [b_contar(r, 4, 4), b_tantos_como(r, 2, 4)]),
    ("El número 4", "Grafía y cantidad del 4.",
     lambda r: [b_trazo(r, ["4"], 6), b_contar(r, 3, 4)]),
    ("Series AB", "Reconocer un patrón de repetición simple.",
     lambda r: [b_unir(r, [("🔴🔵🔴", "🔵"), ("⭐🌙⭐", "🌙"), ("🍎🍌🍎", "🍌")],
                       "Une cada serie con el dibujo que la continúa.")]),
    ("El triángulo", "Reconocer el triángulo entre otras formas.",
     lambda r: [b_formas(r, ["triangulo", "circulo"]), b_colorear(r, 2, 5)]),
    ("Contar hasta 5", "Conteo hasta cinco.",
     lambda r: [b_contar(r, 4, 5), b_colorear(r, 2, 5)]),
    ("El número 5", "Grafía y cantidad del 5.",
     lambda r: [b_trazo(r, ["5"], 6), b_contar(r, 3, 5)]),
    ("Grande, mediano y pequeño", "Seriar por tamaño en tres niveles.",
     lambda r: [b_concepto(r, [("🐘", "grande"), ("🐕", "mediano"), ("🐜", "pequeño")],
                           "Ordena del más GRANDE al más PEQUEÑO escribiendo 1, 2 y 3.")]),
    ("Series con formas", "Continuar patrones con figuras.",
     lambda r: [b_formas(r, ["circulo", "cuadrado", "triangulo"]), b_emparejar(r, 3)]),
    ("Tantos como", "Correspondencia uno a uno.",
     lambda r: [b_tantos_como(r, 4, 5)]),
    ("Repasa del 1 al 5", "Afianzar la grafía de 1 a 5.",
     lambda r: [b_trazo(r, ["1", "2", "3", "4", "5"], 4)]),
    ("El primero y el último", "Nociones de orden en una fila.",
     lambda r: [b_concepto(r, [("🚗", "el primero"), ("🚚", "el último"), ("🚕", "el primero")],
                           "Colorea el PRIMERO de cada fila y tacha el ÚLTIMO.")]),
    ("Cuenta y une", "Asociar colección y numeral.",
     lambda r: [b_unir(r, [("🍎🍎", "2"), ("⭐⭐⭐", "3"), ("🐸", "1"), ("🎈🎈🎈🎈", "4")],
                       "Une cada grupo con su número.")]),
    ("Colorea la cantidad", "Producir una cantidad dada.",
     lambda r: [b_colorear(r, 4, 5)]),
    ("Repaso del 1 al 5", "Evaluación del curso.",
     lambda r: [b_contar(r, 3, 5), b_trazo(r, ["1", "2", "3", "4", "5"], 3), b_comparar(r, 3, 5, True)]),
]

CURSO_4 = [
    ("Repaso del 1 al 5", "Recuperar lo aprendido el curso anterior.",
     lambda r: [b_contar(r, 3, 5), b_trazo(r, ["1", "2", "3", "4", "5"], 4)]),
    ("El número 6", "Grafía y cantidad del 6.",
     lambda r: [b_trazo(r, ["6"], 6), b_contar(r, 3, 6)]),
    ("El número 7", "Grafía y cantidad del 7.",
     lambda r: [b_trazo(r, ["7"], 6), b_contar(r, 3, 7)]),
    ("Contar hasta 7", "Conteo hasta siete.",
     lambda r: [b_contar(r, 4, 7), b_colorear(r, 2, 7)]),
    ("El número 8", "Grafía y cantidad del 8.",
     lambda r: [b_trazo(r, ["8"], 6), b_contar(r, 3, 8)]),
    ("Series ABC", "Patrones de tres elementos.",
     lambda r: [b_emparejar(r, 4), b_colorear(r, 2, 6)]),
    ("El número 9", "Grafía y cantidad del 9.",
     lambda r: [b_trazo(r, ["9"], 6), b_contar(r, 3, 9)]),
    ("Más que y menos que", "Comparar numerales.",
     lambda r: [b_comparar(r, 6, 9)]),
    ("El número 10", "Grafía y cantidad del 10.",
     lambda r: [b_trazo(r, ["10"], 5), b_contar(r, 3, 10)]),
    ("Contar hasta 10", "Conteo hasta diez.",
     lambda r: [b_contar(r, 4, 10), b_tantos_como(r, 2, 6)]),
    ("Sumar con dibujos", "Iniciación a la suma con apoyo gráfico.",
     lambda r: [b_operaciones(r, "+", 6, 5, enunciado="Cuenta los dibujos de cada caja y suma.")]),
    ("Anterior y posterior", "Situar un número en la serie.",
     lambda r: [b_vecinos(r, 5, 10)]),
    ("Rectángulo y óvalo", "Ampliar el repertorio de formas.",
     lambda r: [b_formas(r, ["rectangulo", "ovalo", "circulo", "cuadrado"])]),
    ("Sumas hasta 6", "Sumar dentro de la primera decena.",
     lambda r: [b_operaciones(r, "+", 8, 6)]),
    ("De menor a mayor", "Ordenar una colección de numerales.",
     lambda r: [b_rodear(r, 4, 10, "mayor"), b_rodear(r, 3, 10, "menor")]),
    ("Sumas hasta 8", "Aumentar el rango de la suma.",
     lambda r: [b_operaciones(r, "+", 8, 8)]),
    ("Descomponer el 5", "Composición y descomposición del 5.",
     lambda r: [b_descomponer(r, 5, 4)]),
    ("Quitar: primeras restas", "Iniciación a la resta.",
     lambda r: [b_operaciones(r, "-", 6, 8)]),
    ("Sumas hasta 10", "Consolidar la suma hasta 10.",
     lambda r: [b_operaciones(r, "+", 8, 10)]),
    ("Repaso del 1 al 10", "Evaluación del curso.",
     lambda r: [b_contar(r, 3, 10), b_operaciones(r, "+", 5, 10), b_comparar(r, 4, 10)]),
]

CURSO_5 = [
    ("Repaso del 1 al 10", "Recuperar la serie del 1 al 10.",
     lambda r: [b_contar(r, 3, 10), b_vecinos(r, 4, 10)]),
    ("Trazo del 1 al 10", "Afianzar la grafía de todos los dígitos.",
     lambda r: [b_trazo(r, ["1", "2", "3", "4", "5"], 4), b_trazo(r, ["6", "7", "8", "9", "10"], 4)]),
    ("Sumas hasta 10", "Sumar sin superar la decena.",
     lambda r: [b_operaciones(r, "+", 10, 10)]),
    ("Restas hasta 10", "Restar dentro de la primera decena.",
     lambda r: [b_operaciones(r, "-", 10, 10)]),
    ("Descomponer el 10", "Los pares que suman 10.",
     lambda r: [b_descomponer(r, 10, 6)]),
    ("Números del 11 al 15", "Ampliar la serie más allá de la decena.",
     lambda r: [b_trazo(r, ["11", "12", "13", "14", "15"], 3), b_vecinos(r, 4, 15)]),
    ("Anterior y posterior", "Moverse por la serie numérica.",
     lambda r: [b_vecinos(r, 6, 15)]),
    ("Mayor, menor o igual", "Usar los signos de comparación.",
     lambda r: [b_comparar(r, 8, 15)]),
    ("Sumas en vertical", "Colocar la suma en columnas.",
     lambda r: [b_operaciones(r, "+", 6, 15, "vertical")]),
    ("Números del 16 al 20", "Completar la serie hasta 20.",
     lambda r: [b_trazo(r, ["16", "17", "18", "19", "20"], 3), b_vecinos(r, 4, 20)]),
    ("Series de 2 en 2", "Conteo salteado.",
     lambda r: [b_serie(r, 3, 2, 10, 6)]),
    ("Restas en vertical", "Colocar la resta en columnas.",
     lambda r: [b_operaciones(r, "-", 6, 15, "vertical")]),
    ("Figuras geométricas", "Identificar seis formas planas.",
     lambda r: [b_formas(r, ["circulo", "cuadrado", "triangulo", "rectangulo", "ovalo", "rombo"])]),
    ("Problemas de sumar", "Aplicar la suma a una situación real.",
     lambda r: [b_problema(r, "+", 3, 15), b_operaciones(r, "+", 4, 15)]),
    ("Problemas de restar", "Aplicar la resta a una situación real.",
     lambda r: [b_problema(r, "-", 3, 15), b_operaciones(r, "-", 4, 15)]),
    ("Ordenar hasta 20", "Comparar y ordenar numerales.",
     lambda r: [b_rodear(r, 5, 20, "mayor"), b_rodear(r, 4, 20, "menor")]),
    ("Los dobles", "Sumar un número consigo mismo.",
     lambda r: [b_dobles(r, 6, 10)]),
    ("Sumas de tres números", "Sumar con sumandos mayores.",
     lambda r: [b_operaciones(r, "+", 8, 18)]),
    ("La decena", "Reconocer el 10 como unidad de agrupación.",
     lambda r: [b_descomponer(r, 10, 6), b_serie(r, 2, 10, 10, 5)]),
    ("Repaso del 1 al 20", "Evaluación del curso.",
     lambda r: [b_operaciones(r, "+", 5, 20), b_operaciones(r, "-", 5, 20), b_problema(r, "+", 2, 20)]),
]

CURSO_6 = [
    ("Números hasta 30", "Leer y escribir números de dos cifras.",
     lambda r: [b_vecinos(r, 6, 30), b_rodear(r, 4, 30, "mayor")]),
    ("Decenas y unidades", "Descomponer en decenas y unidades.",
     lambda r: [b_descomponer(r, 10, 6), b_serie(r, 3, 10, 20, 5)]),
    ("Sumas sin llevar", "Sumar dos cifras sin reagrupar.",
     lambda r: [b_operaciones(r, "+", 8, 40, "vertical", llevando=False)]),
    ("Restas sin llevar", "Restar dos cifras sin reagrupar.",
     lambda r: [b_operaciones(r, "-", 8, 40, "vertical", llevando=False)]),
    ("Series de 2 y de 5", "Conteo salteado con dos pasos distintos.",
     lambda r: [b_serie(r, 3, 2, 20, 7), b_serie(r, 3, 5, 20, 6)]),
    ("Números hasta 50", "Ampliar el rango numérico.",
     lambda r: [b_vecinos(r, 6, 50), b_comparar(r, 6, 50)]),
    ("Comparar dos cifras", "Comparar números de dos cifras.",
     lambda r: [b_comparar(r, 10, 50)]),
    ("Problemas de sumar", "Resolver problemas de una operación.",
     lambda r: [b_problema(r, "+", 4, 40)]),
    ("Problemas de restar", "Resolver problemas de una operación.",
     lambda r: [b_problema(r, "-", 4, 40)]),
    ("El reloj: en punto", "Leer horas en punto.",
     lambda r: [b_reloj(r, 6, "en punto")]),
    ("Números hasta 100", "Completar la centena.",
     lambda r: [b_vecinos(r, 6, 100), b_rodear(r, 4, 100, "mayor")]),
    ("Series de 10 en 10", "Contar de diez en diez.",
     lambda r: [b_serie(r, 4, 10, 50, 7)]),
    ("Dobles y mitades", "Relacionar el doble y la mitad.",
     lambda r: [b_dobles(r, 8, 20)]),
    ("Tres sumandos", "Sumar números mayores.",
     lambda r: [b_operaciones(r, "+", 8, 60)]),
    ("El euro: monedas", "Contar dinero con monedas de 1 y 2 €.",
     lambda r: [b_monedas(r, 6)]),
    ("Anterior y posterior hasta 100", "Situar números dentro de la centena.",
     lambda r: [b_vecinos(r, 8, 100)]),
    ("Sumas llevando", "Iniciación a la reagrupación.",
     lambda r: [b_operaciones(r, "+", 8, 60, "vertical", llevando=True)]),
    ("Figuras y sus lados", "Contar lados y vértices.",
     lambda r: [b_formas(r, ["triangulo", "cuadrado", "rectangulo", "rombo"],
                         "Repasa cada figura y escribe debajo cuántos lados tiene.")]),
    ("Problemas variados", "Elegir la operación correcta.",
     lambda r: [b_problema(r, "+", 3, 50), b_problema(r, "-", 2, 50)]),
    ("Repaso hasta 100", "Evaluación del curso.",
     lambda r: [b_operaciones(r, "+", 6, 80, "vertical"), b_operaciones(r, "-", 6, 80, "vertical"),
                b_problema(r, "+", 2, 60)]),
]

CURSO_7 = [
    ("Números hasta 200", "Leer y escribir números de tres cifras.",
     lambda r: [b_vecinos(r, 8, 200), b_comparar(r, 6, 200)]),
    ("Sumas llevando", "Sumar reagrupando unidades.",
     lambda r: [b_operaciones(r, "+", 9, 99, "vertical", llevando=True)]),
    ("Restas llevando", "Restar reagrupando decenas.",
     lambda r: [b_operaciones(r, "-", 9, 99, "vertical", llevando=True)]),
    ("Centenas, decenas y unidades", "Valor posicional en tres cifras.",
     lambda r: [b_serie(r, 4, 100, 200, 6), b_comparar(r, 6, 300)]),
    ("La tabla del 2", "Memorizar la tabla del 2.",
     lambda r: [b_tabla(r, 2)]),
    ("La tabla del 5", "Memorizar la tabla del 5.",
     lambda r: [b_tabla(r, 5)]),
    ("La tabla del 10", "Memorizar la tabla del 10.",
     lambda r: [b_tabla(r, 10)]),
    ("Problemas de dos operaciones", "Encadenar dos operaciones.",
     lambda r: [b_problema(r, "+", 3, 80), b_problema(r, "-", 2, 80)]),
    ("El reloj: y media", "Leer las medias horas.",
     lambda r: [b_reloj(r, 6, "y media")]),
    ("La tabla del 3", "Memorizar la tabla del 3.",
     lambda r: [b_tabla(r, 3)]),
    ("Números hasta 500", "Ampliar hasta la quinta centena.",
     lambda r: [b_vecinos(r, 8, 500), b_rodear(r, 5, 500, "mayor")]),
    ("La tabla del 4", "Memorizar la tabla del 4.",
     lambda r: [b_tabla(r, 4)]),
    ("Doble y triple", "Multiplicar por 2 y por 3.",
     lambda r: [b_operaciones(r, "x", 8, 3)]),
    ("El reloj: y cuarto", "Leer los cuartos de hora.",
     lambda r: [b_reloj(r, 6, "y cuarto")]),
    ("Medidas: cm y m", "Estimar y comparar longitudes.",
     lambda r: [b_unir(r, [("Un lápiz", "15 cm"), ("Una puerta", "2 m"),
                           ("Una hormiga", "1 cm"), ("Un autobús", "10 m")],
                       "Une cada objeto con la medida más razonable.")]),
    ("Números hasta 1000", "Completar el millar.",
     lambda r: [b_vecinos(r, 8, 999), b_comparar(r, 8, 999)]),
    ("Multiplicar por 2 y 3", "Aplicar las tablas aprendidas.",
     lambda r: [b_operaciones(r, "x", 10, 3)]),
    ("Problemas con dinero", "Resolver problemas con euros.",
     lambda r: [b_monedas(r, 6), b_problema(r, "-", 2, 50)]),
    ("Mitad, tercio y cuarto", "Iniciación a las fracciones.",
     lambda r: [b_descomponer(r, 12, 6), b_operaciones(r, "x", 6, 4)]),
    ("Repaso final", "Evaluación global del curso.",
     lambda r: [b_operaciones(r, "+", 5, 200, "vertical", llevando=True),
                b_operaciones(r, "-", 5, 200, "vertical"), b_tabla(r, 5),
                b_problema(r, "+", 2, 100)]),
]

CURRICULO = {2: CURSO_2, 3: CURSO_3, 4: CURSO_4, 5: CURSO_5, 6: CURSO_6, 7: CURSO_7}
